import type { BirthInput } from "./types";

export type Celeb = BirthInput & { who: string; note: string };

export const CELEBS: Celeb[] = [
  { name: "孔子", who: "思想家", note: "传统纪年为鲁襄公二十二年", gender: "male", year: -551, month: 9, day: 28, hour: 12, minute: 0, cityId: "jinan" },
  { name: "屈原", who: "诗人", note: "楚人，生年据年谱约数", gender: "male", year: -340, month: 3, day: 1, hour: 12, minute: 0, cityId: "wuhan" },
  { name: "司马迁", who: "史家", note: "龙门，生年有两说", gender: "male", year: -145, month: 6, day: 1, hour: 12, minute: 0, cityId: "xian" },
  { name: "张衡", who: "太史令", note: "南阳西鄂", gender: "male", year: 78, month: 1, day: 1, hour: 12, minute: 0, cityId: "zhengzhou" },
  { name: "曹操", who: "政治家", note: "沛国谯", gender: "male", year: 155, month: 7, day: 18, hour: 12, minute: 0, cityId: "hefei" },
  { name: "诸葛亮", who: "政治家", note: "琅琊阳都，传说层另见玄学史", gender: "male", year: 181, month: 7, day: 23, hour: 12, minute: 0, cityId: "jinan" },
  { name: "李白", who: "诗人", note: "碎叶或江油，取常见谱", gender: "male", year: 701, month: 2, day: 28, hour: 12, minute: 0, cityId: "chengdu" },
  { name: "杜甫", who: "诗人", note: "巩县", gender: "male", year: 712, month: 2, day: 12, hour: 12, minute: 0, cityId: "zhengzhou" },
  { name: "韩愈", who: "文人", note: "河阳", gender: "male", year: 768, month: 8, day: 1, hour: 12, minute: 0, cityId: "zhengzhou" },
  { name: "白居易", who: "诗人", note: "新郑", gender: "male", year: 772, month: 2, day: 28, hour: 12, minute: 0, cityId: "zhengzhou" },
  { name: "苏轼", who: "文学家", note: "眉山，年谱", gender: "male", year: 1037, month: 1, day: 8, hour: 12, minute: 0, cityId: "chengdu" },
  { name: "李清照", who: "词人", note: "约元丰七年章丘", gender: "female", year: 1084, month: 3, day: 13, hour: 12, minute: 0, cityId: "jinan" },
  { name: "朱熹", who: "理学", note: "尤溪", gender: "male", year: 1130, month: 10, day: 18, hour: 12, minute: 0, cityId: "fuzhou" },
  { name: "王阳明", who: "心学", note: "余姚", gender: "male", year: 1472, month: 10, day: 31, hour: 12, minute: 0, cityId: "hangzhou" },
  { name: "徐光启", who: "历算", note: "上海", gender: "male", year: 1562, month: 4, day: 24, hour: 12, minute: 0, cityId: "shanghai" },
  { name: "黄宗羲", who: "思想家", note: "余姚", gender: "male", year: 1610, month: 9, day: 24, hour: 12, minute: 0, cityId: "hangzhou" },
  { name: "曹雪芹", who: "小说家", note: "生年有两说，取 1715", gender: "male", year: 1715, month: 7, day: 1, hour: 12, minute: 0, cityId: "beijing" },
  { name: "纪晓岚", who: "学者", note: "献县", gender: "male", year: 1724, month: 7, day: 26, hour: 12, minute: 0, cityId: "tianjin" },
  { name: "林则徐", who: "政治家", note: "侯官", gender: "male", year: 1785, month: 8, day: 30, hour: 12, minute: 0, cityId: "fuzhou" },
  { name: "曾国藩", who: "政治家", note: "湘乡", gender: "male", year: 1811, month: 11, day: 26, hour: 7, minute: 0, cityId: "changsha" },
  { name: "李鸿章", who: "政治家", note: "合肥", gender: "male", year: 1823, month: 2, day: 15, hour: 12, minute: 0, cityId: "hefei" },
  { name: "慈禧", who: "政治人物", note: "叶赫那拉，日期据谱", gender: "female", year: 1835, month: 11, day: 29, hour: 12, minute: 0, cityId: "beijing" },
  { name: "光绪", who: "皇帝", note: "载湉", gender: "male", year: 1871, month: 8, day: 14, hour: 12, minute: 0, cityId: "beijing" },
  { name: "孙中山", who: "政治家", note: "香山翠亨", gender: "male", year: 1866, month: 11, day: 12, hour: 4, minute: 0, cityId: "guangzhou" },
  { name: "梁启超", who: "思想家", note: "新会", gender: "male", year: 1873, month: 2, day: 23, hour: 12, minute: 0, cityId: "guangzhou" },
  { name: "鲁迅", who: "文学家", note: "绍兴，公开时辰午前", gender: "male", year: 1881, month: 9, day: 25, hour: 8, minute: 0, cityId: "hangzhou" },
  { name: "胡适", who: "学者", note: "绩溪", gender: "male", year: 1891, month: 12, day: 17, hour: 12, minute: 0, cityId: "hefei" },
  { name: "毛泽东", who: "政治人物", note: "韶山", gender: "male", year: 1893, month: 12, day: 26, hour: 8, minute: 0, cityId: "changsha" },
  { name: "宋庆龄", who: "政治人物", note: "文昌", gender: "female", year: 1893, month: 1, day: 27, hour: 12, minute: 0, cityId: "haikou" },
  { name: "梅兰芳", who: "京剧", note: "北京", gender: "male", year: 1894, month: 10, day: 22, hour: 12, minute: 0, cityId: "beijing" },
  { name: "周恩来", who: "政治人物", note: "淮安", gender: "male", year: 1898, month: 3, day: 5, hour: 12, minute: 0, cityId: "nanjing" },
  { name: "宋美龄", who: "政治人物", note: "文昌", gender: "female", year: 1898, month: 3, day: 5, hour: 12, minute: 0, cityId: "haikou" },
  { name: "老舍", who: "作家", note: "北京", gender: "male", year: 1899, month: 2, day: 3, hour: 12, minute: 0, cityId: "beijing" },
  { name: "张爱玲", who: "作家", note: "上海", gender: "female", year: 1920, month: 9, day: 30, hour: 12, minute: 0, cityId: "shanghai" },
  { name: "金庸", who: "作家", note: "海宁", gender: "male", year: 1924, month: 3, day: 10, hour: 12, minute: 0, cityId: "hangzhou" },
  { name: "巴金", who: "作家", note: "成都", gender: "male", year: 1904, month: 11, day: 25, hour: 12, minute: 0, cityId: "chengdu" },
  { name: "邓丽君", who: "歌手", note: "云林", gender: "female", year: 1953, month: 1, day: 29, hour: 19, minute: 0, cityId: "taipei" },
  { name: "李小龙", who: "武术家", note: "旧金山，有精确时", gender: "male", year: 1940, month: 11, day: 27, hour: 7, minute: 12, cityId: "sf" },
  { name: "成龙", who: "演员", note: "香港", gender: "male", year: 1954, month: 4, day: 7, hour: 12, minute: 0, cityId: "hk" },
  { name: "宫崎骏", who: "导演", note: "东京", gender: "male", year: 1941, month: 1, day: 5, hour: 12, minute: 0, cityId: "tokyo" },
  { name: "黑泽明", who: "导演", note: "东京", gender: "male", year: 1910, month: 3, day: 23, hour: 12, minute: 0, cityId: "tokyo" },
  { name: "三岛由纪夫", who: "作家", note: "东京", gender: "male", year: 1925, month: 1, day: 14, hour: 12, minute: 0, cityId: "tokyo" },
  { name: "川端康成", who: "作家", note: "大阪", gender: "male", year: 1899, month: 6, day: 14, hour: 12, minute: 0, cityId: "tokyo" },
  { name: "牛顿", who: "自然哲学", note: "儒略历 1642-12-25，格里历 1643-1-4", gender: "male", year: 1643, month: 1, day: 4, hour: 1, minute: 0, cityId: "london" },
  { name: "莱布尼茨", who: "哲学家", note: "莱比锡，取巴黎经度近似", gender: "male", year: 1646, month: 7, day: 1, hour: 12, minute: 0, cityId: "paris" },
  { name: "康德", who: "哲学家", note: "柯尼斯堡", gender: "male", year: 1724, month: 4, day: 22, hour: 5, minute: 0, cityId: "paris" },
  { name: "歌德", who: "诗人", note: "法兰克福，公开时辰午前", gender: "male", year: 1749, month: 8, day: 28, hour: 12, minute: 0, cityId: "paris" },
  { name: "贝多芬", who: "作曲家", note: "波恩，时间存疑", gender: "male", year: 1770, month: 12, day: 16, hour: 11, minute: 30, cityId: "paris" },
  { name: "拿破仑", who: "政治人物", note: "阿雅克肖，常见记录午前", gender: "male", year: 1769, month: 8, day: 15, hour: 11, minute: 0, cityId: "paris" },
  { name: "雨果", who: "作家", note: "贝桑松", gender: "male", year: 1802, month: 2, day: 26, hour: 22, minute: 30, cityId: "paris" },
  { name: "达尔文", who: "博物学家", note: "什鲁斯伯里", gender: "male", year: 1809, month: 2, day: 12, hour: 6, minute: 0, cityId: "london" },
  { name: "马克思", who: "思想家", note: "特里尔", gender: "male", year: 1818, month: 5, day: 5, hour: 2, minute: 0, cityId: "paris" },
  { name: "托尔斯泰", who: "作家", note: "雅斯纳亚", gender: "male", year: 1828, month: 9, day: 9, hour: 12, minute: 0, cityId: "paris" },
  { name: "尼采", who: "哲学家", note: "勒肯", gender: "male", year: 1844, month: 10, day: 15, hour: 10, minute: 0, cityId: "paris" },
  { name: "梵高", who: "画家", note: "津德尔特，有洗礼记录", gender: "male", year: 1853, month: 3, day: 30, hour: 11, minute: 0, cityId: "paris" },
  { name: "弗洛伊德", who: "精神分析", note: "弗莱堡", gender: "male", year: 1856, month: 5, day: 6, hour: 18, minute: 30, cityId: "paris" },
  { name: "特斯拉", who: "发明家", note: "斯米连，夜半", gender: "male", year: 1856, month: 7, day: 10, hour: 0, minute: 0, cityId: "paris" },
  { name: "萧伯纳", who: "剧作家", note: "都柏林", gender: "male", year: 1856, month: 7, day: 26, hour: 12, minute: 0, cityId: "london" },
  { name: "居里夫人", who: "科学家", note: "华沙", gender: "female", year: 1867, month: 11, day: 7, hour: 12, minute: 0, cityId: "paris" },
  { name: "甘地", who: "政治人物", note: "博尔本德尔", gender: "male", year: 1869, month: 10, day: 2, hour: 7, minute: 0, cityId: "bangkok" },
  { name: "爱因斯坦", who: "物理学家", note: "乌尔姆，公开出生时间 11:30", gender: "male", year: 1879, month: 3, day: 14, hour: 11, minute: 30, cityId: "paris" },
  { name: "毕加索", who: "画家", note: "马拉加", gender: "male", year: 1881, month: 10, day: 25, hour: 23, minute: 15, cityId: "paris" },
  { name: "凯恩斯", who: "经济学家", note: "剑桥", gender: "male", year: 1883, month: 6, day: 5, hour: 12, minute: 0, cityId: "london" },
  { name: "卡夫卡", who: "作家", note: "布拉格", gender: "male", year: 1883, month: 7, day: 3, hour: 7, minute: 0, cityId: "paris" },
  { name: "希特勒", who: "政治人物", note: "布劳瑙，公开户籍", gender: "male", year: 1889, month: 4, day: 20, hour: 18, minute: 30, cityId: "paris" },
  { name: "卓别林", who: "演员", note: "伦敦", gender: "male", year: 1889, month: 4, day: 16, hour: 20, minute: 0, cityId: "london" },
  { name: "蒋中正", who: "政治人物", note: "溪口，常见谱录午时", gender: "male", year: 1887, month: 10, day: 31, hour: 12, minute: 0, cityId: "hangzhou" },
  { name: "图灵", who: "数学家", note: "伦敦", gender: "male", year: 1912, month: 6, day: 23, hour: 2, minute: 15, cityId: "london" },
  { name: "曼德拉", who: "政治人物", note: "姆韦佐", gender: "male", year: 1918, month: 7, day: 18, hour: 12, minute: 0, cityId: "london" },
  { name: "伊丽莎白二世", who: "君主", note: "伦敦，有精确时", gender: "female", year: 1926, month: 4, day: 21, hour: 2, minute: 40, cityId: "london" },
  { name: "玛丽莲·梦露", who: "演员", note: "洛杉矶，有出生证明", gender: "female", year: 1926, month: 6, day: 1, hour: 9, minute: 30, cityId: "la" },
  { name: "马丁·路德·金", who: "民权", note: "亚特兰大", gender: "male", year: 1929, month: 1, day: 15, hour: 12, minute: 0, cityId: "nyc" },
  { name: "奥黛丽·赫本", who: "演员", note: "布鲁塞尔", gender: "female", year: 1929, month: 5, day: 4, hour: 3, minute: 0, cityId: "paris" },
  { name: "沃伦·巴菲特", who: "投资", note: "奥马哈", gender: "male", year: 1930, month: 8, day: 30, hour: 12, minute: 0, cityId: "nyc" },
  { name: "猫王", who: "歌手", note: "图珀洛，有记录午前", gender: "male", year: 1935, month: 1, day: 8, hour: 4, minute: 35, cityId: "nyc" },
  { name: "约翰·列侬", who: "音乐", note: "利物浦", gender: "male", year: 1940, month: 10, day: 9, hour: 18, minute: 30, cityId: "london" },
  { name: "穆罕默德·阿里", who: "拳击", note: "路易斯维尔", gender: "male", year: 1942, month: 1, day: 17, hour: 18, minute: 30, cityId: "nyc" },
  { name: "史蒂芬·霍金", who: "物理学家", note: "牛津", gender: "male", year: 1942, month: 1, day: 8, hour: 12, minute: 0, cityId: "london" },
  { name: "比尔·盖茨", who: "企业家", note: "西雅图", gender: "male", year: 1955, month: 10, day: 28, hour: 21, minute: 0, cityId: "sf" },
  { name: "乔布斯", who: "企业家", note: "旧金山，有收养记录", gender: "male", year: 1955, month: 2, day: 24, hour: 19, minute: 15, cityId: "sf" },
  { name: "马云", who: "企业家", note: "杭州", gender: "male", year: 1964, month: 9, day: 10, hour: 12, minute: 0, cityId: "hangzhou" },
  { name: "马化腾", who: "企业家", note: "汕头", gender: "male", year: 1971, month: 10, day: 29, hour: 12, minute: 0, cityId: "shenzhen" },
];
