import type { Person, EventItem, Story } from "./history";

export const EXTRA_PEOPLE: Person[] = [
  { id: "luoxia", name: "落下闳", years: "西汉", dynasty: "han", tags: ["历法"], summary: "巴郡人。太初历的运算者之一。", body: "汉武帝改历，邓平、落下闳、唐都参与。落下闳运算转历，用八十一分律历。太初以后，岁首在正月，二十四节气成为国家时间。后来八字、奇门、择日，都站在这套节气上。", links: ["taichu", "simaqian"] },
  { id: "liuxin", name: "刘歆", years: "前50?–23", dynasty: "han", tags: ["历法", "三统"], summary: "三统历。把历法、音律、易数拧在一起。", body: "刘歆在《汉书·律历志》写三统历，用黄钟八十一分，又用易数说历。这是「以理说天」的高峰，也是后来被实测不断修正的起点。术数爱引用三统，往往忘了它首先是一部官方历。", links: ["luoxia", "zhangheng"] },
  { id: "liuhong", name: "刘洪", years: "约 130–210", dynasty: "han", tags: ["历法", "月行"], summary: "乾象历。第一次认真处理月行迟疾。", body: "刘洪作乾象历，引入月行迟疾、近点月。日食预报因此改善。没有这一步，后来的交食、罗睺计都在中文里会更含糊。", links: ["zhangheng"] },
  { id: "zuchongzhi", name: "祖冲之", years: "429–500", dynasty: "wei", tags: ["历法", "圆周率"], summary: "大明历。引入岁差，改闰周。", body: "祖冲之指出何承天历的疏失，用三百九十一年一百四十四闰，并引入岁差。宋孝武帝未及用。他的圆周率常被单独提出，历法才是他的本职：让天行与闰余对齐。", links: ["yixing"] },
  { id: "liuzhuo", name: "刘焯", years: "544–610", dynasty: "sui", tags: ["历法", "等间距"], summary: "皇极历。二次内插的先声。", body: "刘焯皇极历用等间距二次差，处理日行盈缩。隋朝未颁用。李淳风、一行后来的步气朔，都要经过这一层数学。术数书里的「盈缩」，源头是历法，不是命理。", links: ["lichunfeng", "yixing"] },
  { id: "nangong", name: "南宫说", years: "唐", dynasty: "sui", tags: ["测影"], summary: "开元测影的执行者之一。", body: "开元十二年，南宫说等人在滑州、汴州等地立表测影。一行总其事。没有这些实地数字，「日影千里差一寸」不会被拆掉。", links: ["yixing"] },
  { id: "caoshui", name: "曹士蒍", years: "唐", dynasty: "sui", tags: ["符天历", "七政"], summary: "符天历。把印度历法因素带进民间通书。", body: "曹士蒍符天历以显庆五年为历元，行于民间。七政四余的民用算法，有一层是从这里来的：宿度、罗计，不必等钦天监。", links: ["line-qizheng", "kaiyuan"] },
  { id: "yelv", name: "耶律楚材", years: "1190–1244", dynasty: "yuan", tags: ["历算", "庚午元历"], summary: "辽金元之际的历算名臣。", body: "耶律楚材随成吉思汗西征，用里差（经度）改正月食。庚午元历是他的作品。中原历法第一次被迫认真对待「东西里差」。", links: ["guoshoujing"] },
  { id: "zhamaluding", name: "札马鲁丁", years: "13 世纪", dynasty: "yuan", tags: ["回回历", "西域"], summary: "回回司天台。把伊斯兰天文仪器带进大都。", body: "札马鲁丁造七件西域仪象，撰万年历。回回历与授时历并行，是元明「两种天」的制度来源。七政通书里的「西域」，有一脉在此。", links: ["guoshoujing", "xuguangqi"] },
  { id: "wangxun", name: "王恂", years: "1235–1281", dynasty: "yuan", tags: ["授时历"], summary: "授时历的数学负责人。", body: "郭守敬测，王恂算。授时历用招差术、弧矢割圆，废除积年日法。中国古典历法在这里几乎走到头。后来的时宪历，是另一套几何。", links: ["guoshoujing"] },
  { id: "beilin", name: "贝琳", years: "明", dynasty: "ming", tags: ["七政", "回回"], summary: "七政推步。把回回法写成汉语手册。", body: "贝琳辑《七政推步》，让不会阿拉伯文的人也能算罗计。明代通书、星命，大量靠这类二手译写。", links: ["line-qizheng"] },
  { id: "wangxichan", name: "王锡阐", years: "1628–1682", dynasty: "qing", tags: ["历算"], summary: "晓庵。会通中西而不肯盲从西法。", body: "王锡阐与梅文鼎并称。他用中法术语消化第谷体系，又批评西法的疏失。术数史读到清初，会看见：通书必须在两种几何里选边，或假装没看见。", links: ["meiwen"] },
  { id: "daizhen", name: "戴震", years: "1724–1777", dynasty: "qing", tags: ["考据", "勾股"], summary: "以考据治历算、治经。", body: "戴震校《周髀》《九章》，把术数从「神秘」拉回「名物度数」。清学的这一刀，让风角、分野在知识界降格，却在民间通书里原样活着。", links: ["zhangheng"] },
  { id: "ruanyuan", name: "阮元", years: "1764–1849", dynasty: "qing", tags: ["畴人传"], summary: "《畴人传》。给历算家立传。", body: "阮元编畴人传，从羲和写到清人。术数人物第一次被放进「科学家传」的框架。谁算进畴人、谁留在方技，本身就是一条近代分界。", links: ["meiwen"] },
  { id: "jiaoxun", name: "焦循", years: "1763–1820", dynasty: "qing", tags: ["易学"], summary: "雕菰楼易学。用数学讲易。", body: "焦循《易章句》《易图略》，把旁通、时行写成可演算的条例。这是易学的代数化，不是占卜手册。六爻家偶尔借他的词，体系并不相同。", links: ["line-liuyao"] },
  { id: "rentieqiao", name: "任铁樵", years: "清", dynasty: "qing", tags: ["八字", "滴天髓"], summary: "注《滴天髓》。清代命理的难经。", body: "任铁樵把滴天髓从口诀变成分析：通关、病药、从弱从强。民国命书大半是在和他对话。神煞派不喜欢他，格局派离不开他。", links: ["wanminying", "line-bazi"] },
  { id: "xulewu", name: "徐乐吾", years: "1886–1948", dynasty: "mod", tags: ["八字"], summary: "民国命理的印刷人。", body: "徐乐吾评注子平真诠、穷通宝鉴，让这些书进入城市书店。命理从师徒口传到铅字，是近代术数史的一件大事。", links: ["rentieqiao", "line-bazi"] },
  { id: "weiqianli", name: "韦千里", years: "1911–1988", dynasty: "mod", tags: ["八字"], summary: "千里命稿。民国都市命理。", body: "韦千里在上海写命稿，案例化、口语化。子平术离开村塾，进入报章。读他，能看见二十世纪的城市如何消费「命」。", links: ["xulewu"] },
  { id: "liangxiangrun", name: "梁湘润", years: "1930–2013", dynasty: "mod", tags: ["八字", "子平"], summary: "台湾子平文献派。", body: "梁湘润强调用古文献校正流俗口诀，写滴天髓、子平基础。当代华文命理的「文献自觉」，很大一部分从他开始。", links: ["xulewu", "line-bazi"] },
  { id: "dorotheus", name: "多罗西斯", years: "1 世纪", dynasty: "west", tags: ["占星", "三分"], summary: "Carmen Astrologicum。三分、福点、婚姻。", body: "多罗西斯的五卷诗体占星，经波斯—阿拉伯传到拉丁世界。托勒密重理论，他重技法。西洋本命里的福点、三分日夜主，有一层是他。", links: ["ptolemy", "valens"] },
  { id: "mashallah", name: "马沙拉", years: "约 740–815", dynasty: "west", tags: ["占星", "阿拉伯"], summary: "Māshāʾallāh。大翻译运动的占星工匠。", body: "马沙拉是犹太裔占星家，在巴格达写合盘、年运、问卜。阿拉伯占星把波斯、印度、希腊焊在一起，再西传。中世纪欧洲的本命，经过这一站。", links: ["abumashar"] },
  { id: "abumashar", name: "阿布·马沙尔", years: "787–886", dynasty: "west", tags: ["占星", "历史占星"], summary: "大年份。用星说王朝。", body: "阿布·马沙尔把木土会合写成世界史的节拍。这是西洋版的「皇极」：用周期讲治乱。后来的宗教论战，常常拿他开刀。", links: ["mashallah", "shaoyong"] },
  { id: "albiruni", name: "比鲁尼", years: "973–1048", dynasty: "west", tags: ["印度", "测量"], summary: "印度志。比较希腊与印度占星。", body: "比鲁尼在伽色尼写印度的宿、九曜、达沙，并测地球半径。他是少数同时懂两边术语的人。七政与印占在中文里相遇，可以借他当翻译。", links: ["parashara", "line-vedic"] },
  { id: "bonatti", name: "博纳蒂", years: "13 世纪", dynasty: "west", tags: ["占星", "霍拉"], summary: "Liber Astronomiae。中世纪拉丁占星大全。", body: "圭多·博纳蒂服务意大利城市与贵族，写问卜、选举、本命。Lilly 以前，欧洲霍拉的手册就是这类书。", links: ["lilly"] },
  { id: "morin", name: "莫兰", years: "1583–1656", dynasty: "west", tags: ["占星", "宫主"], summary: "Astrologia Gallica。宫主星与因果链。", body: "让-巴蒂斯特·莫兰用三十宫、本质尊贵、因果链，把占星写成近乎逻辑学。当代古典占星复兴，常从他的宫主法入口。", links: ["lilly", "ptolemy"] },
  { id: "alanleo", name: "艾伦·利奥", years: "1860–1917", dynasty: "west", tags: ["占星", "心理"], summary: "现代占星的印刷教父。", body: "艾伦·利奥把占星从霍拉转向性格与灵魂。二十世纪报纸占星、太阳星座，都从这条坡下来。中文「心理占星」的上游在此。", links: ["line-west"] },
  { id: "rudhyar", name: "鲁德亚", years: "1895–1985", dynasty: "west", tags: ["占星", "人文"], summary: "人文占星。把本命当成长过程。", body: "戴恩·鲁德亚用荣格和进化论重写星盘。宫位变成发展阶段，土星变成成年礼。当代心理占星的词汇表，大量是他的。", links: ["alanleo", "line-west"] },
  { id: "jingfang-person", name: "京房", years: "前77–前37", dynasty: "han", tags: ["六爻", "纳甲"], summary: "京氏易。把卦变成可配年月日的仪器。", body: "京房字君明，以卦气、纳甲、八宫世应说灾异，终因政治而死。后来六爻的骨骼——世应、纳甲、飞伏——都从京氏来。读他，要分开：作为历法化的易，和作为朝堂上的预言。", links: ["line-liuyao"] },
  { id: "guanlu", name: "管辂", years: "209–256", dynasty: "wei", tags: ["占", "传说"], summary: "三国术数的明星。正史有传，神异在笔记。", body: "《三国志》管辂传写他明《周易》、风角、占筮，能预言生死。裴注更神。后世卜者喜欢认他作同行。史与术在他身上已经开始分叉。", links: ["zhuge", "line-liuyao"] },
  { id: "guopu", name: "郭璞", years: "276–324", dynasty: "wei", tags: ["风水", "葬书"], summary: "注《山海经》《尔雅》。葬书托名于他。", body: "郭璞是文学家、训诂家，也是占筮者。《葬书》是否他作，学界怀疑。但「葬者乘生气」这套话，必须挂一个魏晋名士，才进得了后来的风水谱系。", links: ["line-fengshui"] },
  { id: "laiwenjun", name: "赖布衣", years: "宋", dynasty: "song", tags: ["风水", "天星"], summary: "赖文俊。天星派口碑。", body: "赖布衣在风水传说里几乎万能：看皇城、看坟墓、留诗谶。可靠史料少。赣派形势之外，天星（以星卦配龙水）常归到他名下。", links: ["yangjunsong", "line-fengshui"] },
  { id: "jiangdahong", name: "蒋大鸿", years: "1616–1714?", dynasty: "qing", tags: ["风水", "玄空"], summary: "地理辨正。玄空飞星的近代祖师。", body: "蒋平阶（大鸿）攻驳三合，标举玄空。清代以后的理气之争，多从他的书开始。形势派骂他，理气派认他。", links: ["line-fengshui"] },
  { id: "shenshao", name: "沈括", years: "1031–1095", dynasty: "song", tags: ["梦溪", "历算"], summary: "梦溪笔谈。记极星、指南、历法。", body: "沈括测极星离天极三度有余，记指南针的偏角。他不是术士，但他记下的观测，后来的历法和罗盘都用得上。梦溪里还有「纳甲」「六壬」的见闻，是宋代知识人如何看待术数的切片。", links: ["yixing"] },
  { id: "ouyang", name: "欧阳修", years: "1007–1072", dynasty: "song", tags: ["史", "批评"], summary: "不信谶纬的史官。", body: "欧阳修修《新唐书》《新五代史》，对祥瑞灾异持保留。宋代士人里有一条线：可以谈易理，不愿谈占验。术数史要把这条反对的声音也写上，否则只剩江湖。", links: ["shaoyong"] },
];

export const EXTRA_EVENTS: EventItem[] = [
  { id: "sn185", year: 185, title: "中平二年客星（SN 185）", dynasty: "han", tags: ["客星", "天象"], kind: "sky", body: "《后汉书》记客星出南门。现代天文学指为超新星 SN 185。中文「客星」传统第一次可以和河外星残骸对上号。" },
  { id: "sn1006", year: 1006, title: "景德三年客星（SN 1006）", dynasty: "song", tags: ["客星", "天象"], kind: "sky", body: "周克明等记「周伯星」。亮度可能达到 −7 等。宋人用祥瑞语言写下了南天最亮超新星之一。" },
  { id: "sn1572", year: 1572, title: "隆庆六年客星（第谷新星）", dynasty: "ming", tags: ["客星", "天象"], kind: "sky", body: "中国、朝鲜、欧洲同时记录仙后座超新星。第谷用来证明恒星天可变。中文记录仍称客星，不称新星。" },
  { id: "sn1604", year: 1604, title: "万历客星（开普勒新星）", dynasty: "ming", tags: ["客星", "天象"], kind: "sky", body: "开普勒新星。徐光启一辈已经能看到：西洋新法与中土客星记录可以对勘。" },
  { id: "eclipse-720", year: -720, title: "春秋日食", dynasty: "pre", tags: ["日食", "天象"], kind: "sky", body: "《春秋》隐公三年「日有食之」。鲁史把日食写进政治时间。后来的月食修刑、日食修德，都从这种书法来。" },
  { id: "halley-240", year: -240, title: "秦始皇世彗星", dynasty: "pre", tags: ["彗星", "天象"], kind: "sky", body: "《史记》记始皇世彗星。哈雷彗星回推之一。秦人把孛当作兵象，史官照记。" },
  { id: "halley-1066", year: 1066, title: "治平彗星 / 欧洲哈雷", dynasty: "song", tags: ["彗星"], kind: "sky", body: "哈雷 1066 年回归。欧洲织进诺曼征服；宋人记彗出。同一颗彗星，两种政治语法。" },
  { id: "halley-1456", year: 1456, title: "景泰七年彗星", dynasty: "ming", tags: ["彗星"], kind: "sky", body: "哈雷 1456。欧洲在祈祷，明人在《英宗实录》里写「彗见」。" },
  { id: "halley-1759", year: 1759, title: "哈雷首次被预报后回归", dynasty: "qing", tags: ["彗星", "西学"], kind: "sky", body: "哈雷死后，这是第一次按牛顿力学预报而出现的回归。钦天监此时已用时宪历，中西记录可以对到同一天。" },
  { id: "halley-1910", year: 1910, title: "哈雷彗星过地球轨道", dynasty: "mod", tags: ["彗星"], kind: "sky", body: "1910 年地球穿过彗尾，报纸恐慌。术数语言第一次大规模让位给大众传媒的科学新闻。" },
  { id: "halley-1986", year: 1986, title: "哈雷回归与探测", dynasty: "mod", tags: ["彗星"], kind: "sky", body: "国际哈雷探测。中文世界从此把「孛」彻底写成「哈雷彗星」。玄学史在这里可以画一条线：观测胜过占辞。" },
  { id: "taichu-inst", year: -104, title: "太初改历成为制度", dynasty: "han", tags: ["历法"], kind: "chronicle", body: "太初元年十一月甲子朔旦冬至，历元落成。此后术数凡用节气、用月建，都默认这一次国家改历。" },
  { id: "sifen", year: 85, title: "四分历", dynasty: "han", tags: ["历法"], kind: "chronicle", body: "后汉四分历，岁实 365.25。太初八十一分的神秘整数被部分放弃。历法开始更像测量。" },
  { id: "daye", year: 608, title: "大业历", dynasty: "sui", tags: ["历法"], kind: "chronicle", body: "张胄玄大业历。隋历屡改，说明南北朝积累的岁差、日食问题，已经逼朝廷不断换算法。" },
  { id: "linde", year: 665, title: "麟德历", dynasty: "sui", tags: ["历法"], kind: "chronicle", body: "李淳风麟德历，用定朔。民间「月初一不一定见新月」的经验，被官方承认。" },
  { id: "xuanming", year: 822, title: "宣明历", dynasty: "sui", tags: ["历法"], kind: "chronicle", body: "徐昂宣明历，对日食三差有处理。日本长期用宣明历，东亚术数时间有一条是这条历。" },
  { id: "shoushi-promulgated", year: 1281, title: "授时历颁行", dynasty: "yuan", tags: ["历法"], kind: "chronicle", body: "至元十八年授时历。无积年，无日法，用实测。古典中法的顶点。明清通书的节气，很长一段时间还在用它的骨架。" },
  { id: "shixian", year: 1645, title: "时宪历", dynasty: "qing", tags: ["历法", "西学"], kind: "chronicle", body: "汤若望时宪历，用第谷体系。顺治颁行。民间通书改称时宪书。中国的「官天」从此是西洋几何。" },
  { id: "daotong", year: 1742, title: "历象考成后编", dynasty: "qing", tags: ["历法"], kind: "chronicle", body: "引入牛顿力学修正。钦天监的天，和术士的天，差距变成制度。" },
  { id: "ziping-yuanhai", year: 1250, title: "渊海子平类书成形", dynasty: "song", tags: ["八字"], kind: "chronicle", body: "托名徐子平的材料在宋元被编成类书。四柱、月令、格局从此可以「查」。" },
  { id: "sanming", year: 1560, title: "三命通会刊行前后", dynasty: "ming", tags: ["八字"], kind: "chronicle", body: "万民英把神煞与格局编成可以检索的厚书。命理的类书时代开始。" },
  { id: "ditui", year: 1630, title: "滴天髓注本流行", dynasty: "ming", tags: ["八字"], kind: "chronicle", body: "托名刘基的注本在明末清初流传。不堆神煞、讲气势的路子，成为后来的「高级命理」。" },
  { id: "qimen-sm", year: 1600, title: "奇门遁甲烟波钓叟赋写定", dynasty: "ming", tags: ["奇门"], kind: "chronicle", body: "明清奇门的普及，靠赋、诀、盘图，而不是靠黄帝阴符。时家超神接气的争论，也在这个时期写死。" },
  { id: "liuren-daquan-print", year: 1785, title: "六壬大全通行", dynasty: "qing", tags: ["六壬"], kind: "chronicle", body: "《六壬大全》把课体、毕法、神将编成教材。壬学从口传变成可以自修的书。" },
  { id: "gold-needle", year: 1786, title: "蒋大鸿地理辨正刊刻影响扩大", dynasty: "qing", tags: ["风水"], kind: "chronicle", body: "玄空与三合的论战进入印刷。风水从此不只是看龙看水，还有一套罗盘上的「元运」。" },
  { id: "christian-1647", year: 1647, title: "Christian Astrology", dynasty: "west", tags: ["占星"], kind: "chronicle", body: "Lilly 的英文霍拉教材。占星离开拉丁，进入城市作坊。" },
  { id: "theosophy-ast", year: 1890, title: "神智学会与现代占星", dynasty: "west", tags: ["占星"], kind: "chronicle", body: "艾伦·利奥一辈把占星改成性格与转世。太阳星座报纸栏，是这条路的下游。" },
  { id: "computer-ephe", year: 1980, title: "计算机星历进入民间", dynasty: "mod", tags: ["工具"], kind: "chronicle", body: "瑞士星历、个人电脑。本命盘从查表变成按键。中文紫微、七政软件，也在此后二十年出现。星阙这类离线应用，是这一页的手机版。" },
];

export const EXTRA_STORIES: Story[] = [
  { id: "s-gan-de-jup", title: "甘德与木星", source: "开元占经引甘氏", person: "gande", body: "甘氏有木星「见伏」的周期。现代天文学史用这些佚文讨论战国是否已用岁星纪年。数字不必精确，重要的是：星已经从神话变成可以数的对象。" },
  { id: "s-zhang-seism", title: "地动仪", source: "后汉书·张衡传", person: "zhangheng", body: "陇西地震，长安的龙吐丸。传记把仪器写成灵验。术数史要记住：张衡同时造浑象和写《思玄赋》，观测与辞章在他身上还不分裂。" },
  { id: "s-yixing-taiyi", title: "一行与大衍", source: "新唐书·历志", person: "yixing", body: "大衍历以易数名，以实测行。名字是术，内容是测。后来的人只看见「大衍」，看不见南北测影的表格。" },
  { id: "s-guo-gaocheng", title: "郭守敬登高城", source: "元史·郭守敬传", person: "guoshoujing", body: "郭守敬在阳城等地测影，又通水利。授时历不是书斋产品。把「观象」从占辞里救出来的，是这些人把尺子带到现场。" },
  { id: "s-xu-calendar-war", title: "崇祯改历之争", source: "明史·历志", person: "xuguangqi", body: "徐光启引西法，冷守中、魏文魁攻驳。争论在朝堂上用日食裁判。输赢不在口才，在食分时刻。术数如果还只背口诀，已经离开了这场裁判。" },
  { id: "s-lilly-fire", title: "Lilly 与伦敦大火", source: "Christian Astrology / 审判记录", person: "lilly", body: "Lilly 被怀疑预知 1666 大火。霍拉占星在城市里有政治风险。中文的「妖言惑众」条款，在欧洲也有孪生兄弟。" },
  { id: "s-shaoyong-luoyang", title: "邵雍安乐窝", source: "宋史·道学", person: "shaoyong", body: "邵雍居洛阳，名其居为安乐窝。皇极经世是在这种闲里写的。后来铁板神数托他的名，把闲里的历史代数，改成市井的一句断语。" },
];
