import { EXTRA_EVENTS, EXTRA_PEOPLE, EXTRA_STORIES } from "./history-extra";
import { CLASSICS } from "./classics";

export type Dynasty = { id: string; name: string; from: number; to: number };

export const DYNASTIES: Dynasty[] = [
  { id: "pre", name: "先秦", from: -1100, to: -207 },
  { id: "han", name: "两汉", from: -206, to: 220 },
  { id: "wei", name: "魏晋", from: 220, to: 589 },
  { id: "sui", name: "隋唐", from: 581, to: 907 },
  { id: "song", name: "宋", from: 960, to: 1279 },
  { id: "yuan", name: "元", from: 1271, to: 1368 },
  { id: "ming", name: "明", from: 1368, to: 1644 },
  { id: "qing", name: "清", from: 1644, to: 1911 },
  { id: "mod", name: "近代", from: 1912, to: 2026 },
  { id: "west", name: "西学", from: -400, to: 2026 },
];

export type Person = {
  id: string;
  name: string;
  years: string;
  dynasty: string;
  tags: string[];
  summary: string;
  body: string;
  links: string[];
};

export const PEOPLE: Person[] = [
  {
    id: "gande",
    name: "甘德",
    years: "战国",
    dynasty: "pre",
    tags: ["占星", "星经"],
    summary: "齐人，与石申并称，是现存最早的中土黄道星官传统源头之一。",
    body: "《史记·天官书》司马贞索隐引甘氏星经。甘德观测木星，留下接近行星周期的记录。后世《开元占经》大量保存甘、石佚文，是中国星官与占辞的早期地层。",
    links: ["shishen", "simaqian", "tianxiang-1054"],
  },
  {
    id: "shishen",
    name: "石申",
    years: "战国",
    dynasty: "pre",
    tags: ["占星", "星经"],
    summary: "魏人。石氏星经给出若干恒星的赤道坐标，是世界最早的星表之一。",
    body: "石申（或石申夫）的星表经汉代转写，保存在唐代《开元占经》。现代天文学史用岁差回推，认为部分数据可追溯到战国。石氏与甘氏共同构成中国星官的骨架，后来陈卓把甘、石、巫咸三家星官汇总。",
    links: ["gande", "chenzhuo"],
  },
  {
    id: "simaqian",
    name: "司马迁",
    years: "前145?–前86?",
    dynasty: "han",
    tags: ["天官", "史"],
    summary: "《史记·天官书》把星官、分野、日食、彗孛写成正史的一部分。",
    body: "天官书不是占书，是史官的天空：中宫、东宫、南宫、西宫、北宫，以及五星见伏、日食、客星。此后二十四史的《天文志》都沿这条线写。它也记录了哈雷彗星一类的「孛」，成为今天回推古代天象的文献底座。",
    links: ["gande", "halley-bc"],
  },
  {
    id: "zhangheng",
    name: "张衡",
    years: "78–139",
    dynasty: "han",
    tags: ["浑天", "仪器"],
    summary: "浑天说、水运浑象、候风地动仪。《灵宪》讲天体生成与月食。",
    body: "张衡任太史令，把观测、仪象和理论放在同一职位里。浑天说以天如鸡子、地如黄，给后来的历法一个几何图像。月食「蔽于地」的判断，已经是光学遮挡，而不是神话。",
    links: ["simaqian", "yixing"],
  },
  {
    id: "chenzhuo",
    name: "陈卓",
    years: "西晋",
    dynasty: "wei",
    tags: ["星官"],
    summary: "汇总甘、石、巫咸三家星官，形成后世星图的标准名录。",
    body: "陈卓任太史令，把三家星官合为 283 官、1464 星的系统。隋丹元子《步天歌》即在这套名录上歌唱，方便记诵。今天中文星空里的「紫微、太微、天市」三垣二十八宿，仍能看见这一层。",
    links: ["gande", "shishen"],
  },
  {
    id: "lichunfeng",
    name: "李淳风",
    years: "602–670",
    dynasty: "sui",
    tags: ["历法", "乙巳占", "三式"],
    summary: "麟德历、乙巳占、注释《周髀》。唐代官方占星的集大成者。",
    body: "李淳风在太史局修历，同时写《乙巳占》，把分野、风角、云气、三式材料系统化。他注《周髀算经》，承认盖天的算法价值。民间把推背图挂在他和袁天罡名下，那是后来的传说层，与他作为历官的工作要分开看。",
    links: ["yuantiangang", "yixing", "line-sanshi"],
  },
  {
    id: "yuantiangang",
    name: "袁天罡",
    years: "唐初",
    dynasty: "sui",
    tags: ["相术", "风水"],
    summary: "相术与风水传说极盛。正史有传，神异故事多出笔记。",
    body: "两唐书有袁天罡，以相人闻名。后世风水、推背、拆字都爱借他的名字。《太平广记》收其相武后、相杜淹等条，可见唐人已把他写成半神半史。研究术数史时，要把「袁天罡」当作一个传说集群，而不是每一条都信。",
    links: ["lichunfeng", "taiping"],
  },
  {
    id: "yixing",
    name: "僧一行",
    years: "683–727",
    dynasty: "sui",
    tags: ["历法", "子午线"],
    summary: "大衍历。组织天下测影，相当于一次子午线长度测量。",
    body: "一行与梁令瓒造黄道游仪、水运浑天。开元十二年派人在南北多个地点测日影，南至交州，北至铁勒。这不是现代大地测量，但第一次用实测否定「日影千里差一寸」的旧说。大衍历把阴阳、卦气和步气朔写在一起，是唐历的高峰。",
    links: ["zhangheng", "lichunfeng"],
  },
  {
    id: "yangjunsong",
    name: "杨筠松",
    years: "唐末",
    dynasty: "sui",
    tags: ["风水"],
    summary: "形势派开山。赣南杨公风水的祖师。",
    body: "杨筠松（杨救贫）的可靠史料很少，但赣南、闽西、粤北的风水传授都认他。《撼龙经》《疑龙经》《葬法倒杖》托名于他，讲龙、砂、穴、水。这是中国风水「看形」的主干，后来的理气各派都要回来对形势。",
    links: ["line-fengshui"],
  },
  {
    id: "chentuan",
    name: "陈抟",
    years: "871?–989",
    dynasty: "song",
    tags: ["先天图", "内丹"],
    summary: "隐士。先天图经他传到邵雍一线。",
    body: "陈抟居华山，宋太宗召见。朱熹以后的叙述里，先天图从陈抟、种放、穆修传到李之才、邵雍。真伪有争议，但「先天八卦」作为一套不同于文王后天的图式，从此进入儒者的世界，不再只是术家口诀。",
    links: ["shaoyong"],
  },
  {
    id: "shaoyong",
    name: "邵雍",
    years: "1011–1077",
    dynasty: "song",
    tags: ["皇极", "先天"],
    summary: "《皇极经世》。以元会运世把历史装进先天卦序。",
    body: "邵雍字尧夫，居洛阳。皇极经世用 12×30×12×30 的时间树，把尧以来的治乱对应到卦上。这不是占卜手册，是一种历史哲学；后来术家把它改成推命、梅花易数的近亲。程颢称他「内圣外王」。先天六十四卦圆图成为宋以后数术的一张底图。",
    links: ["chentuan", "line-huangji"],
  },
  {
    id: "xuziping",
    name: "徐子平",
    years: "五代–宋",
    dynasty: "song",
    tags: ["八字"],
    summary: "把李虚中的三柱扩展为四柱，年、月、日、时并重。",
    body: "韩愈写过李虚中以年月日干支推命。徐子平（徐居易）加上时柱，并用月令格局论用神，形成后来《渊海子平》的骨干。子平术的要点不是神煞堆砌，而是月令、格局、用神、岁运。明清命书无论怎么加材料，骨架仍是这一套。",
    links: ["line-bazi", "wanminying"],
  },
  {
    id: "wanminying",
    name: "万民英",
    years: "1522–1603",
    dynasty: "ming",
    tags: ["八字", "星学"],
    summary: "《三命通会》《星学大成》。明代官修气质的集大成。",
    body: "万民英字育吾。三命通会把神煞、格局、干支关系编成类书，是明清命理先生的案头书。星学大成则整理七政四余。他让「士人也可以谈命」变得体面，同时也把术数写得更繁。读他，要会删。",
    links: ["xuziping", "line-qizheng"],
  },
  {
    id: "liuji",
    name: "刘基",
    years: "1311–1375",
    dynasty: "ming",
    tags: ["术数", "传说"],
    summary: "刘伯温。真实的是开国谋臣；传说的是烧饼歌、神数。",
    body: "刘基字伯温，元进士，佐朱元璋。正史里他是文章与兵谋，不是江湖术士。烧饼歌、滴天髓真伪、神数托名，都是明中叶以后的附加层。《太平广记》式的神异叙事在明代小说里再次爆发，刘伯温成为「能知未来的开国军师」。",
    links: ["yuantiangang"],
  },
  {
    id: "lai",
    name: "赖文俊",
    years: "宋",
    dynasty: "song",
    tags: ["风水", "理气"],
    summary: "赖布衣。理气与天星的传说人物。",
    body: "赖文俊名下的《催官篇》讲天星、龙穴与官禄。宋代风水从杨公形势分出理气一支，用卦例、三合、纳甲来定坐向。明清以后三合、玄空、飞星都从这里长出来。",
    links: ["yangjunsong", "line-fengshui"],
  },
  {
    id: "ptolemy",
    name: "托勒密",
    years: "约 100–170",
    dynasty: "west",
    tags: ["占星", "西洋"],
    summary: "《四书》Tetrabiblos。希腊占星的教科书。",
    body: "克罗狄斯·托勒密在亚历山大城写《至大论》和《四书》。后者把黄道、宫位、相位、限期整理成可教学的体系，中世纪阿拉伯与拉丁世界都靠它。中国要到明末译书才间接碰到这套语言。",
    links: ["lilly", "kepler"],
  },
  {
    id: "kepler",
    name: "开普勒",
    years: "1571–1630",
    dynasty: "west",
    tags: ["天文学", "占星"],
    summary: "行星定律的发现者，同时仍为人起星盘。",
    body: "开普勒给华伦斯坦等人写过占星意见。他批评宫廷占星的粗糙，但相信大会合与历史节奏有关。科学史常把他「洗成」纯天文学家；术数史则应看见：直到十七世纪，观测与占还坐在同一张桌子上。",
    links: ["ptolemy"],
  },
  {
    id: "lilly",
    name: "威廉·利里",
    years: "1602–1681",
    dynasty: "west",
    tags: ["占星", "霍拉"],
    summary: "Christian Astrology。英国内战时期的卜卦占星。",
    body: "Lilly 的书把霍拉、择时、本命写成英文教材，并在伦敦用星盘评论时局。这是西洋占星从宫廷拉丁走向城市印刷的关键一步。今天英语世界的古典占星复兴，仍从他出发。",
    links: ["ptolemy"],
  },
  {
    id: "chuci",
    name: "京房",
    years: "前77–前37",
    dynasty: "han",
    tags: ["京氏易", "纳甲"],
    summary: "京氏易。把卦、世应、纳甲、飞伏做成可占的系统。",
    body: "京房学于焦延寿，以六十四卦配岁、以世应纳甲论飞伏。他的易不是义理，是一套时间与灾异的仪器。后来火珠林、纳甲六爻，都从京氏这一支下来。他也因论灾异下狱，死于贬所——术数进入政治，风险一直在。",
    links: ["line-liuyao"],
  },
  {
    id: "yangxiong",
    name: "扬雄",
    years: "前53–18",
    dynasty: "han",
    tags: ["太玄"],
    summary: "《太玄》。以三为数，八十一首拟易。",
    body: "扬雄以为易是二进制的极致，于是造太玄：一方、二方、三方，四重，八十一首。它没有成为占卜主流，却保留了一种「可以另造一套宇宙代数」的自由。司马光、邵雍都读过它。",
    links: ["shaoyong"],
  },
  {
    id: "guopu",
    name: "郭璞",
    years: "276–324",
    dynasty: "wei",
    tags: ["风水", "葬书"],
    summary: "托名《葬书》的源头人物。博学，注尔雅、山海经。",
    body: "郭璞是文学家和方士型人物。《葬书》是否他作有争议，但风水「乘生气」这一句话从此被当作经典。他注《山海经》，把地理神异和士人知识接在一起。",
    links: ["yangjunsong", "line-fengshui"],
  },
  {
    id: "xun",
    name: "一行之后的曹士蒍",
    years: "唐",
    dynasty: "sui",
    tags: ["符天历", "七政"],
    summary: "符天历。民间七政的算法传统。",
    body: "曹士蒍的符天历用数码和印度写法，在民间流传，与官方大衍历并行。后世通书、七政四余的「民用算法」，有一层是从这条民间历下来的。",
    links: ["yixing", "line-qizheng"],
  },
  {
    id: "guigu",
    name: "鬼谷子",
    years: "战国",
    dynasty: "pre",
    tags: ["纵横", "传说"],
    summary: "纵横家祖师。术数书常托他的名，史料里他更像一个学派符号。",
    body: "《史记》里苏秦、张仪都「事鬼谷先生」。传世《鬼谷子》讲捭阖、反应，是游说术，不是占书。后来阴符、揣摩、命相都爱挂这个名字。读术数史，要把「鬼谷」当作一个传说集群：它说明战国已有职业日者，并不等于每一本托名书都是他写的。",
    links: ["simajizhu", "zhuge"],
  },
  {
    id: "simajizhu",
    name: "司马季主",
    years: "汉初",
    dynasty: "han",
    tags: ["日者", "卜"],
    summary: "《史记·日者列传》的主人公。士人问卜，他反过来问士人。",
    body: "贾谊、宋忠在长安东市见司马季主坐肆而卜。他批评朝士「居官而致乱」，把卜筮说成一种不肯同流的知识。这篇列传是中文世界最早把「日者」写成有思想的人，而不只是街边把戏。后来谈卜的人，常从这里给自己找体面。",
    links: ["simaqian", "yanjunping"],
  },
  {
    id: "luoxiahong",
    name: "落下闳",
    years: "西汉",
    dynasty: "han",
    tags: ["历法"],
    summary: "巴郡人。太初历的运算者之一，浑天仪象的早期实践者。",
    body: "汉武帝改历，邓平、落下闳、唐都等人参与。落下闳运算转历，用浑天。太初以后，节气、朔望成为国家时间；八字、择日、奇门都站在这套节气上。术数看起来在占，底座其实是历。",
    links: ["taichu", "zhangheng"],
  },
  {
    id: "dongfangshuo",
    years: "前154?–前93?",
    name: "东方朔",
    dynasty: "han",
    tags: ["射覆", "传说"],
    summary: "武帝弄臣。射覆、滑稽，后来被写成半仙。",
    body: "正史里东方朔以滑稽得亲近，也以《答客难》自辩。射覆是猜覆盖之物，近于占，但更近于机智。《汉武故事》以后，他变成岁星下凡。术数故事喜欢这种「朝堂上的先知」，要把史与小说分开。",
    links: ["simaqian", "s-dongfang"],
  },
  {
    id: "jiaoyanshou",
    name: "焦延寿",
    years: "西汉",
    dynasty: "han",
    tags: ["易林", "焦氏易"],
    summary: "京房之师。《焦氏易林》以一卦变六十四，凡四千九十六辞。",
    body: "焦赣字延寿，梁人。他的易以「一卦变六十四」把时间切细，京房从这里走到纳甲、世应。传世《易林》是否全出其手有争议，但「以卦气写灾异」这条路，是从焦、京进入汉政的。后来火珠林、六爻，都还看得到这层。",
    links: ["chuci", "line-liuyao"],
  },
  {
    id: "yanjunping",
    name: "严君平",
    years: "西汉",
    dynasty: "han",
    tags: ["卜", "老子"],
    summary: "成都卖卜，日得百钱即收肆读《老子》。",
    body: "扬雄少时从君平游。君平以卜筮「劝善」，有邪恶问者则依蓍龟告以利害。这是把占卜写成伦理教育，不是预测机器。蜀中后来的道家、卜肆传统，常把这个姿态当成祖师。",
    links: ["yangxiong", "simajizhu"],
  },
  {
    id: "guanlu",
    name: "管辂",
    years: "209–256",
    dynasty: "wei",
    tags: ["占", "射覆"],
    summary: "三国术士。正史有传，射覆、风角、卦的故事极盛。",
    body: "《三国志》管辂传是术数人物传记里写得最细的一篇：射覆、卦、风角、相人，都有情节。裴注更铺张。他留下的不是神通，是当时知识人怎样用易、用风、用星来说话。读他，能看见魏晋术数还没有被后来的门派切开。",
    links: ["guopu", "s-guanlu"],
  },
  {
    id: "lixuzhong",
    name: "李虚中",
    years: "762–813",
    dynasty: "sui",
    tags: ["八字", "三柱"],
    summary: "韩愈为之墓志。以年月日干支推命，是子平的前身。",
    body: "韩愈《殿中侍御史李君墓志铭》写他以人之始生年月日所直日辰干支，参相斟酌，推人寿夭贵贱。还没有时柱。徐子平后来补上时辰，四柱才定型。虚中是「把命从相术里分出来、交给干支」的关键一步。",
    links: ["xuziping", "line-bazi"],
  },
  {
    id: "shenkuo",
    name: "沈括",
    years: "1031–1095",
    dynasty: "song",
    tags: ["梦溪", "天文"],
    summary: "《梦溪笔谈》记陨石、指南、历法、星象，把方术写成可观察的事。",
    body: "沈括任司天监，改历，记「陨石为铁」、磁针偏东、虹的观测。他对卜筮、相、风水并不一概骂倒，但要求「可验」。宋人知识里，术数和格物还坐在同一张桌子上；沈括是这张桌子的书记官。",
    links: ["tianxiang-1054", "shaoyong"],
  },
  {
    id: "guoshoujing",
    name: "郭守敬",
    years: "1231–1316",
    dynasty: "yuan",
    tags: ["历法", "授时"],
    summary: "授时历。测影、简仪，把观测精度推到古典中文世界的高峰。",
    body: "郭守敬与王恂修授时历，用三次差内插，岁实已接近现代回归年。他在河南阳城测影，仪器是简仪、仰仪、圭表。术数用的节气、太阳位置，从此有一套更准的底盘。后来回回历、西洋新法进来，比较的对象仍是授时。",
    links: ["shoushi", "yixing"],
  },
  {
    id: "yeluchucai",
    name: "耶律楚材",
    years: "1190–1244",
    dynasty: "yuan",
    tags: ["占星", "历"],
    summary: "辽皇室后裔，佐成吉思汗。西征时用历与占劝止屠城。",
    body: "楚材通辽、金、中原与回回历法，能算日月食。太祖西征，他以天象谏杀。这是术数进入征服者幕府的典型：不是江湖，是参谋。他编《庚午元历》，也写过《玄风庆会录》一类文字。占与政，在他身上分不开。",
    links: ["guoshoujing", "s-yelu"],
  },
  {
    id: "jiangdahong",
    name: "蒋平阶",
    years: "明末清初",
    dynasty: "qing",
    tags: ["风水", "玄空"],
    summary: "蒋大鸿。玄空挨星的关键传人。",
    body: "蒋平阶字大鸿，著《地理辨正》。他把罗盘理气从三合、过路阴阳里提出来，讲零正、挨星、反吟伏吟。清代玄空、飞星各派几乎都要经过他。形势派骂理气，理气内部又互骂，蒋是这套争论的中轴。",
    links: ["yangjunsong", "line-fengshui"],
  },
  {
    id: "liuxiang",
    name: "刘向",
    years: "前77–前6",
    dynasty: "han",
    tags: ["五行", "洪范"],
    summary: "《洪范五行传》把灾异编成年表，是官方数术的目录学。",
    body: "刘向、刘歆父子整理秘府，把洪范五行与春秋灾异对起来。日食、星孛、地震从此有「传」可查。这不是占书，是国家档案。后来《汉书·五行志》即从此出。术数史若只写江湖，会漏掉这一整层。",
    links: ["simaqian", "jingfang"],
  },
  {
    id: "wangbi",
    name: "王弼",
    years: "226–249",
    dynasty: "wei",
    tags: ["易", "义理"],
    summary: "扫象数。王弼注易，让义理压过占。",
    body: "王弼少年注《周易》《老子》，主张得意忘象。汉易的卦气、纳甲、飞伏被他一笔推到边上。这不是术数内部的改革，是一次从外面把占压下去：易可以不占。此后士人读易走王弼，日者走京房，两条河再也没有真正汇合。",
    links: ["chuci", "line-liuyao"],
  },
  {
    id: "xuguangqi",
    name: "徐光启",
    years: "1562–1633",
    dynasty: "ming",
    tags: ["历法", "西学"],
    summary: "与利玛窦译几何，主持历局，开崇祯历书。",
    body: "徐光启把欧洲天文学引进改历：第谷体系、三角函数、地理经度。他仍用中文写「交食」「五星」，让西法能进钦天监。术数用的时刻、方位，从此有一条西洋测路。后来康熙历狱，争的就是这条路谁说了算。",
    links: ["chongzhen", "ptolemy"],
  },
  {
    id: "meiwen",
    name: "梅文鼎",
    years: "1633–1721",
    dynasty: "qing",
    tags: ["历算"],
    summary: "清初历算大家。会通中西，而不肯把中法说成一无是处。",
    body: "梅文鼎遍治授时、回回、西洋新法，写《历学疑问》。康熙召见。他要证明：中法里有可取的观测与数学，西法是另一套几何。这对术数的意义是：通书、七政、选择，开始必须面对「两种天」。",
    links: ["xuguangqi", "guoshoujing"],
  },
  {
    id: "valens",
    name: "瓦伦斯",
    years: "约 120–175",
    dynasty: "west",
    tags: ["占星", "希腊化"],
    summary: "Vettius Valens。《文选》Anthology 是希腊化占星的工作手册。",
    body: "瓦伦斯在安条克一带写了九卷占星实例：分盘、期限、流年、灵魂与命运。比托勒密更「工匠」。二十世纪古典占星复兴，很大程度上是把瓦伦斯从抄本里救回来。中文世界谈西洋本命、限期，源头有一层是他。",
    links: ["ptolemy", "lilly"],
  },
  {
    id: "parashara",
    name: "帕拉沙拉",
    years: "传说 / 古典",
    dynasty: "west",
    tags: ["印占", "吠陀"],
    summary: "Brihat Parashara Hora Shastra 托名的圣仙。北印占星的骨架。",
    body: "帕拉沙拉体系用恒星黄道、二十七宿（纳沙特拉）、九行星（含罗睺计都）、行星期（达沙）。它与希腊占星在贵霜—笈多时期互借过，又走了另一条：宿、达沙、瑜伽。中文「印占」所排的北印盘，多从此出。",
    links: ["line-vedic", "line-qizheng"],
  },
  {
    id: "tycho",
    name: "第谷",
    years: "1546–1601",
    dynasty: "west",
    tags: ["天文学", "超新星"],
    summary: "1572 年客星。精密观测者，仍为人起星盘。",
    body: "第谷在卡塞尼亚记录仙后座超新星，证明「恒星天也会变」。他的火星数据后来交给开普勒。宫廷里他同样做占星年报。和开普勒一样：观测与占还没有离婚。徐光启引进的，正是第谷这套宇宙。",
    links: ["kepler", "sn1572"],
  },
  {
    id: "zhuge",
    name: "诸葛亮",
    years: "181–234",
    dynasty: "wei",
    tags: ["传说", "兵"],
    summary: "历史是政治家；传说是能借东风的术士。",
    body: "《三国志》里诸葛亮是知人、治军、出师。借东风、奇门、马前课，是宋元以后小说和术数书的附加层。把孔明写成奇门祖师，说明三式一直想找一个道德上无可指摘的英雄。史与术，在他身上分得最清楚。",
    links: ["guanlu", "line-sanshi"],
  },
  ...EXTRA_PEOPLE,
];

export type EventItem = {
  id: string;
  year: number;
  title: string;
  dynasty: string;
  tags: string[];
  body: string;
  kind: "chronicle" | "sky";
  links?: string[];
};

export const EVENTS: EventItem[] = [
  {
    id: "halley-bc",
    year: -613,
    title: "春秋鲁文公十四年彗星",
    dynasty: "pre",
    tags: ["彗星", "天象"],
    kind: "sky",
    body: "《春秋》「有星孛于北斗」。这是中文世界对彗星（孛）的早期可靠记录之一，常被用来回推哈雷彗星。天象进入编年，后来的《天文志》都沿用这种写法。",
  },
  {
    id: "shiji-tian",
    year: -91,
    title: "史记天官书",
    dynasty: "han",
    tags: ["史", "星官"],
    kind: "chronicle",
    body: "司马迁把星官写成正史。分野、五星、日食、客星从此有了官方文体。术数不再只是日者口传。",
  },
  {
    id: "taichu",
    year: -104,
    title: "太初历",
    dynasty: "han",
    tags: ["历法"],
    kind: "chronicle",
    body: "汉武帝颁太初历，以正月为岁首，测二十四节气的框架被国家化。之后所有八字、择日、奇门，都站在这套节气之上。",
  },
  {
    id: "lingxian",
    year: 120,
    title: "张衡《灵宪》",
    dynasty: "han",
    tags: ["浑天"],
    kind: "chronicle",
    body: "月食因地影、天体有生成的秩序。观测仪器和宇宙论第一次在中文里写得这么完整。",
  },
  {
    id: "jingfang",
    year: -45,
    title: "京房纳甲",
    dynasty: "han",
    tags: ["六爻"],
    kind: "chronicle",
    body: "京氏易把卦变成可以配年月日的仪器。世应、纳甲、飞伏成为后来六爻的骨骼。",
  },
  {
    id: "yisi",
    year: 645,
    title: "李淳风《乙巳占》",
    dynasty: "sui",
    tags: ["三式", "占星"],
    kind: "chronicle",
    body: "唐代官方占学的百科。风角、云气、分野、三式材料被编在一起，是后来通书和兵占的上游。",
  },
  {
    id: "dayan",
    year: 728,
    title: "大衍历与测影",
    dynasty: "sui",
    tags: ["历法"],
    kind: "chronicle",
    body: "一行组织南北测影，打破「千里一寸」的教条。历法从经典数字转向实测。",
  },
  {
    id: "tianxiang-1054",
    year: 1054,
    title: "天关客星（超新星）",
    dynasty: "song",
    tags: ["客星", "天象"],
    kind: "sky",
    body: "至和元年，司天监记「客星出天关」。这是蟹状星云超新星。宋人用「客星」这个中性词，留下了现代天体物理仍在引用的光变记录。",
  },
  {
    id: "huangji-book",
    year: 1070,
    title: "皇极经世成书前后",
    dynasty: "song",
    tags: ["皇极"],
    kind: "chronicle",
    body: "邵雍在洛阳把元会运世写成可推的历史代数。数术与理学在这里交叉，也在这里分手。",
  },
  {
    id: "ziping",
    year: 1100,
    title: "子平术成形",
    dynasty: "song",
    tags: ["八字"],
    kind: "chronicle",
    body: "四柱取代三柱，月令格局成为论命的中轴。之后七百年的命书都在注释这件事。",
  },
  {
    id: "kaiyuan",
    year: 729,
    title: "开元占经",
    dynasty: "sui",
    tags: ["占星", "星经"],
    kind: "chronicle",
    body: "瞿昙悉达奉敕编。保存了大量已佚的甘石巫咸星占，并引入印度历法术语。是中国星占文献的仓库。",
  },
  {
    id: "taiping",
    year: 978,
    title: "太平广记",
    dynasty: "song",
    tags: ["笔记", "传说"],
    kind: "chronicle",
    body: "李昉等编五百卷，按神仙、方士、相、卜分门。术数的故事层——谁预言了谁、哪颗星应了哪件事——主要靠它流传。下面「故事」多从此出。",
  },
  {
    id: "tonghui",
    year: 1560,
    title: "三命通会",
    dynasty: "ming",
    tags: ["八字"],
    kind: "chronicle",
    body: "万民英把格局与神煞编成类书，命理从此有了一本「可以查」的厚书。",
  },
  {
    id: "halley-1682",
    year: 1682,
    title: "哈雷彗星回归被确认",
    dynasty: "qing",
    tags: ["彗星", "西学"],
    kind: "sky",
    body: "哈雷用牛顿力学预报回归。中文记录里从春秋到清的「孛」终于可以一条条对上同一颗彗星。史与测在这里合龙。",
  },
  {
    id: "christian-ast",
    year: 1647,
    title: "Christian Astrology 出版",
    dynasty: "west",
    tags: ["占星"],
    kind: "chronicle",
    body: "Lilly 用英文写出霍拉教材。西洋占星进入城市印刷时代。",
    links: ["lilly", "ptolemy"],
  },
  {
    id: "ganshi",
    year: -350,
    title: "甘石星经",
    dynasty: "pre",
    tags: ["占星", "星经"],
    kind: "chronicle",
    body: "甘德、石申的星官与坐标，经汉代转写，唐《开元占经》大量保存。这是中国星占能被回推的第一层文献。",
    links: ["gande", "shishen"],
  },
  {
    id: "hanshu-tian",
    year: 80,
    title: "汉书天文志",
    dynasty: "han",
    tags: ["史", "天象"],
    kind: "chronicle",
    body: "班固把司马迁的天官书变成「志」：记日食、星孛、客星，并配五行传。官方数术的档案体在此定型。",
    links: ["simaqian", "liuxiang"],
  },
  {
    id: "butiang",
    year: 590,
    title: "步天歌",
    dynasty: "sui",
    tags: ["星官"],
    kind: "chronicle",
    body: "丹元子《步天歌》用七字句把三垣二十八宿唱下来。陈卓的星官名录从此可记诵。今天中文星空的口头传统，多半还是这首歌。",
    links: ["chenzhuo"],
  },
  {
    id: "shoushi",
    year: 1280,
    title: "授时历",
    dynasty: "yuan",
    tags: ["历法"],
    kind: "chronicle",
    body: "郭守敬、王恂颁授时历。岁实、朔策都达到古典观测的高峰。通书、七政、选择此后都暗用这套太阳。",
    links: ["guoshoujing"],
  },
  {
    id: "sn1006",
    year: 1006,
    title: "周伯星（超新星）",
    dynasty: "song",
    tags: ["客星", "天象"],
    kind: "sky",
    body: "景德三年，司天监记大星见。这是历史上最亮的银河系超新星之一。宋人用「周伯」一类客星名，留下位置与可见期。",
  },
  {
    id: "sn1572",
    year: 1572,
    title: "第谷客星",
    dynasty: "ming",
    tags: ["客星", "天象"],
    kind: "sky",
    body: "仙后座超新星。第谷证明恒星天会变；明人《实录》也有「客星见」的记录。中西在同一颗新星上各自写下档案。",
    links: ["tycho"],
  },
  {
    id: "sn1604",
    year: 1604,
    title: "开普勒客星",
    dynasty: "ming",
    tags: ["客星", "天象"],
    kind: "sky",
    body: "蛇夫座超新星。开普勒有专书。明朝司天也记了。这是望远镜时代到来前，肉眼能看到的最后一颗银河系超新星。",
    links: ["kepler"],
  },
  {
    id: "halley-1066",
    year: 1066,
    title: "治平三年彗星",
    dynasty: "song",
    tags: ["彗星", "天象"],
    kind: "sky",
    body: "哈雷彗星回归。欧洲有贝叶挂毯；宋有司天记录。同一颗彗星，两边都写成政治预兆，也写成位置档案。",
  },
  {
    id: "chongzhen",
    year: 1634,
    title: "崇祯历书",
    dynasty: "ming",
    tags: ["历法", "西学"],
    kind: "chronicle",
    body: "徐光启、李天经与耶稣会士编成。把第谷体系写进中文历法。入清后改称时宪历。选择、七政从此有一条西法底。",
    links: ["xuguangqi"],
  },
  {
    id: "yuanhai",
    year: 1250,
    title: "渊海子平",
    dynasty: "song",
    tags: ["八字"],
    kind: "chronicle",
    body: "托名徐子平系统的命书。月令、格局、用神、岁运写在一起，是后来三命通会还要回来注释的骨架。",
    links: ["xuziping", "line-bazi"],
  },
  {
    id: "zengshan",
    year: 1680,
    title: "增删卜易",
    dynasty: "qing",
    tags: ["六爻"],
    kind: "chronicle",
    body: "野鹤老人一系。用神、旺衰、应期写得像工作手册。六爻从火珠林的纳甲神煞，转向这一套更短的判断。",
    links: ["line-liuyao"],
  },
  {
    id: "liuren-daquan",
    year: 1786,
    title: "六壬大全",
    dynasty: "qing",
    tags: ["六壬", "三式"],
    kind: "chronicle",
    body: "官修气质的六壬类书。四课三传、天将、年命写在一起。民间壬学此后有了可查的厚本。",
    links: ["line-sanshi"],
  },
  {
    id: "zangshu",
    year: 300,
    title: "葬书",
    dynasty: "wei",
    tags: ["风水"],
    kind: "chronicle",
    body: "托名郭璞。「葬者，乘生气也。」这句话成为形势派的第一义。真伪有争议，影响没有争议。",
    links: ["guopu", "line-fengshui"],
  },
  {
    id: "yanbo",
    year: 880,
    title: "烟波钓叟歌",
    dynasty: "sui",
    tags: ["奇门"],
    kind: "chronicle",
    body: "奇门最常被记诵的歌诀。超神接气、置闰、值符值使，都从这类歌诀进入实践。正史不载作者，术家当教材。",
    links: ["line-sanshi"],
  },
  {
    id: "lingqi-book",
    year: 220,
    title: "灵棋经",
    dynasty: "wei",
    tags: ["灵棋", "太玄"],
    kind: "chronicle",
    body: "十二棋子，上中下，一百二十五卦。旧题东方朔，实为汉魏间的占法。它和太玄一样，证明中文世界不只会用六十四卦。",
    links: ["dongfangshuo", "line-lingqi"],
  },
  {
    id: "xifa",
    year: 1645,
    title: "时宪历",
    dynasty: "qing",
    tags: ["历法", "西学"],
    kind: "chronicle",
    body: "清初用西洋新法颁历。康熙历狱之后，钦天监里中法、西法、回回并存。民间通书逐渐改用新法节气。",
    links: ["xuguangqi", "meiwen"],
  },
  ...EXTRA_EVENTS,
];

export type Story = {
  id: string;
  title: string;
  source: string;
  person?: string;
  body: string;
};

export const STORIES: Story[] = [
  {
    id: "s-yixing-shadow",
    title: "一行测影",
    source: "新唐书·历志",
    person: "yixing",
    body: "开元十二年，太史派人南至交州、北至铁勒测日影。旧说「王畿千里，影差一寸」。实测打破了它。一行没有发明地球，但他让历法离开了经典的整数迷信。",
  },
  {
    id: "s-chunfeng-back",
    title: "李淳风与推背的传说",
    source: "后世托名 / 笔记",
    person: "lichunfeng",
    body: "民间说李淳风与袁天罡对坐推唐以后事，写到某页被喝止，「推背而去」。正史无此书。它说明术数在传说里总想变成历史预言，而史官传统其实更克制：记天象，不编未来。",
  },
  {
    id: "s-yuan-empress",
    title: "袁天罡相武后",
    source: "太平广记",
    person: "yuantiangang",
    body: "广记载袁天罡见幼年武氏，说此郎君子龙睛凤颈，贵人之极。这类故事的功能不是鉴定相术，而是给后来的女主一个「天命早就写在脸上」的叙事。读广记，要当文学，也要当社会心理。",
  },
  {
    id: "s-guest-star",
    title: "天关客星",
    source: "宋会要 / 天文志",
    body: "至和元年五月，晨出东，昼见如太白，至嘉祐元年才没。司天监写「客星」。没有祥瑞文章，只有位置和可见期——所以现代还能用。",
  },
  {
    id: "s-ziping-time",
    title: "为什么必须有时柱",
    source: "子平传统",
    person: "xuziping",
    body: "李虚中只用年月日，一天里出生的人会撞车。加上时辰，四柱才是一个完整的节气切片。子平的贡献是技术性的：把命从「这一天」推进到「这一刻」。",
  },
  {
    id: "s-kepler-wall",
    title: "开普勒给华伦斯坦起盘",
    source: "开普勒书信",
    person: "kepler",
    body: "他写下性格与危险，也写下自己的保留。十七世纪最精确的天体轨道计算者，并不觉得给军人起盘是丢脸的事。丢脸的是谎报精度。",
  },
  {
    id: "s-jizhu",
    title: "东市问卜",
    source: "史记·日者列传",
    person: "simajizhu",
    body: "贾谊、宋忠问司马季主：何居之卑、何行之污。季主大笑，说你们才是才贤而不用。卜肆第一次在正史里反驳朝士。占卜在这里不是答案，是一种不肯入仕的知识姿态。",
  },
  {
    id: "s-guanlu",
    title: "管辂射覆",
    source: "三国志·管辂传",
    person: "guanlu",
    body: "馆陶令诸葛原把燕卵、蜂窠、蜘蛛覆器中，辂卦而中。这类故事后来变成术士的标准技能展示。正史肯写，是因为当时的人真的拿卦当一种推理。",
  },
  {
    id: "s-dongfang",
    title: "东方朔射覆",
    source: "汉书 / 汉武故事",
    person: "dongfangshuo",
    body: "武帝覆守宫于盂下，朔射之曰「臣以为龙又无角，谓之为蛇又有足」。正史当机智，小说当仙术。射覆是占与谜语的交界。",
  },
  {
    id: "s-guopu",
    title: "郭璞葬母",
    source: "晋书 / 世说",
    person: "guopu",
    body: "传说郭璞葬母，去水百步，人以近水为言，曰「当即为陆矣」。其后沙涨。风水故事的原型：看的是生气，应的是地形变迁。当文学读，比当操作手册读更老实。",
  },
  {
    id: "s-shenkuo",
    title: "陨石为铁",
    source: "梦溪笔谈",
    person: "shenkuo",
    body: "治平元年，常州日禺时，天有大声，星陨于宜兴。沈括记其「色如铁，重亦如之」。把「星坠」写成一块可以称的铁，客星故事从此有了一条物证的路。",
  },
  {
    id: "s-yelu",
    title: "西征以天象谏",
    source: "元史 / 湛然居士集",
    person: "yeluchucai",
    body: "太祖要屠城，楚材称天象不可。征服者幕府里的占，功能往往是把杀停下来。术数在这里是政治语言，不是星盘游戏。",
  },
  {
    id: "s-yanping",
    title: "君平卖卜成都",
    source: "汉书·王贡两龚鲍传",
    person: "yanjunping",
    body: "日得百钱足以自养，则闭肆下帘读老子。问卜者，因势导之以善。占卜被写成一种城市里的伦理职业。后来的卜肆，很少再有这个收场。",
  },
  {
    id: "s-zhuge",
    title: "借东风是小说",
    source: "三国演义 / 三国志对照",
    person: "zhuge",
    body: "正史无借东风。奇门、马前课把孔明写成祖师，是宋以后的需要：三式要一个道德英雄。读玄学史，这一条专门用来练习「把传说放回传说」。",
  },
  ...EXTRA_STORIES,
];

export type Lineage = {
  id: string;
  name: string;
  chain: string[];
  body: string;
  technique: string;
};

export const LINEAGES: Lineage[] = [
  {
    id: "line-bazi",
    name: "八字 / 子平",
    technique: "八字",
    chain: ["日者", "李虚中三柱", "徐子平四柱", "渊海子平", "三命通会", "滴天髓 / 穷通宝鉴"],
    body: "从日者到三柱再到四柱。月令格局是核心，神煞是附录。民国以后批命仍多走这一路。",
  },
  {
    id: "line-ziwei",
    name: "紫微斗数",
    technique: "紫微",
    chain: ["唐代星命", "十八飞星传说", "南派 / 北派", "中州 / 三合", "现代软件排盘"],
    body: "紫微的文献地层比子平乱，托名陈抟、吕纯阳者多。可靠的是：它用农历时辰把十四主星安进十二宫，并用四化把流年接通。",
  },
  {
    id: "line-sanshi",
    name: "三式",
    technique: "三式",
    chain: ["汉代太一 / 式盘", "唐乙巳占", "宋以后奇门、六壬、太乙分科", "明清兵占与择时", "当代时家奇门"],
    body: "太乙、六壬、遁甲并称三式。太乙偏国运，六壬偏人事，奇门偏空间与时间的格子。式盘是中国术数里最接近「仪器」的东西。",
  },
  {
    id: "line-liuyao",
    name: "六爻纳甲",
    technique: "六爻",
    chain: ["京氏易", "火珠林", "黄金策", "增删卜易", "今日摇钱"],
    body: "从京房的纳甲飞伏，到火珠林用钱代蓍，再到野鹤老人的用神旺衰。六爻是中国最平民的占法。",
  },
  {
    id: "line-fengshui",
    name: "风水",
    technique: "风水",
    chain: ["郭璞乘生气", "杨筠松形势", "赖氏天星", "三合", "玄空飞星"],
    body: "先看龙砂穴水，再入理气。形势是眼睛，理气是罗盘。两派互相指责，实际都要用地。",
  },
  {
    id: "line-qizheng",
    name: "七政四余",
    technique: "七政",
    chain: ["甘石星经", "印度历法入唐", "符天历", "星学大成", "民用通书"],
    body: "七政是日月五星，四余是罗睺、计都、紫气、月孛。它是中文世界最接近黄道占星的一枝，却用宿度和四余，不走希腊宫制。",
  },
  {
    id: "line-huangji",
    name: "皇极 / 先天",
    technique: "数术",
    chain: ["陈抟先天图", "邵雍皇极经世", "梅花易数", "皇极数民间推法"],
    body: "先天图给了另一套卦序，皇极给了历史的时间树，梅花把数重新变成占。三者常被混称「数理」，其实目的不同。",
  },
  {
    id: "line-west",
    name: "西洋占星",
    technique: "占星",
    chain: ["美索不达米亚月报", "希腊化四书", "阿拉伯大翻译", "中世纪拉丁", " Lilly 与现代心理占星"],
    body: "从国家月报到个人本命，再从宫廷到城市印刷，再到二十世纪心理化。宫制、分盘、推运是它的技术内核。",
  },
  {
    id: "line-vedic",
    name: "吠陀 / 印占",
    technique: "印占",
    chain: ["宿与月站", "希腊化互借", "帕拉沙拉体系", "达沙与瑜伽", "北印盘软件"],
    body: "恒星黄道、二十七宿、九曜、行星期。它和七政四余在罗睺计都上相遇，又在宫制上分手。",
  },
  {
    id: "line-tarot",
    name: "塔罗",
    technique: "塔罗",
    chain: ["意大利纸牌", "马赛体系", "伟特—史密斯", "透特 / 马赛复兴", "心理占卜"],
    body: "从打牌到神秘学再到心理咨询。牌阵是它的「式盘」：位置比单张更重要。",
  },
  {
    id: "line-geomancy",
    name: "地占",
    technique: "地占",
    chain: ["伊斯兰 ramal", "中世纪拉丁", "文艺复兴手册", "十六图形盾牌盘", "现代复原"],
    body: "四点成行，四行成卦，生成十六图形。非洲—伊斯兰—欧洲共用过这套土占，和中国六爻是远亲不是父子。",
  },
  {
    id: "line-jinkou",
    name: "金口诀",
    technique: "金口",
    chain: ["六壬支流", "口头四位", "地分月将人元贵神", "近代写定"],
    body: "把六壬收到四个字上：地分、月将、人元、贵神。短、快、民间。正统壬家有时不认它，它也不等正统。",
  },
  {
    id: "line-taixuan",
    name: "太玄",
    technique: "太玄",
    chain: ["扬雄拟易", "司马光集注", "邵雍旁参", "不再进入主流占卜"],
    body: "三进制的宇宙代数。它失败于成为日用占法，成功于证明：卦的数学可以被重造。",
  },
  {
    id: "line-lingqi",
    name: "灵棋",
    technique: "太玄",
    chain: ["十二棋子", "托名东方朔", "一百二十五卦", "明清刻本"],
    body: "上中下三掷。和太玄一样用「三」，但目的是占，不是拟经。",
  },
  {
    id: "line-tieban",
    name: "铁板神数",
    technique: "数术",
    chain: ["邵雍数理传说", "宋代定数", "明清口诀", "一百二十数"],
    body: "把八字收成一条可查的数。托名邵雍者多。它是皇极经世的民间简化：不要元会运世，只要一句断语。",
  },
  {
    id: "line-heluo",
    name: "河洛理数",
    technique: "数术",
    chain: ["河图洛书", "先天数", "邵雍图", "河洛命理写定"],
    body: "用河图洛书的数给干支加权，合成先天、后天。和子平共用四柱，判断走数理，不走月令格局。",
  },
];

export function personById(id: string) {
  return PEOPLE.find((p) => p.id === id);
}

export function yearLabel(y: number) {
  return y < 0 ? `前${-y}` : String(y);
}

export function searchHistory(q: string) {
  const s = q.trim().toLowerCase();
  if (!s)
    return { people: PEOPLE, events: EVENTS, stories: STORIES, lineages: LINEAGES, classics: CLASSICS };
  const hit = (t: string) => t.toLowerCase().includes(s);
  return {
    people: PEOPLE.filter((p) => hit(p.name) || hit(p.summary) || hit(p.body) || p.tags.some(hit)),
    events: EVENTS.filter((e) => hit(e.title) || hit(e.body) || e.tags.some(hit)),
    stories: STORIES.filter((e) => hit(e.title) || hit(e.body)),
    lineages: LINEAGES.filter((e) => hit(e.name) || hit(e.body) || hit(e.technique)),
    classics: CLASSICS.filter((c) => hit(c.title) || hit(c.author) || hit(c.summary) || c.tags.some(hit)),
  };
}
