/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as AsteroidsRouteImport } from './routes/asteroids'
import { Route as BaziRouteImport } from './routes/bazi'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CelebsRouteImport } from './routes/celebs'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as FeigongRouteImport } from './routes/feigong'
import { Route as FengshuiRouteImport } from './routes/fengshui'
import { Route as GeomancyRouteImport } from './routes/geomancy'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JieqiRouteImport } from './routes/jieqi'
import { Route as JingjueRouteImport } from './routes/jingjue'
import { Route as JinkouRouteImport } from './routes/jinkou'
import { Route as LingqiRouteImport } from './routes/lingqi'
import { Route as LiurenRouteImport } from './routes/liuren'
import { Route as LiuyaoRouteImport } from './routes/liuyao'
import { Route as MeRouteImport } from './routes/me'
import { Route as MingotherRouteImport } from './routes/mingother'
import { Route as NatalRouteImport } from './routes/natal'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as QimenRouteImport } from './routes/qimen'
import { Route as QizhengRouteImport } from './routes/qizheng'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as SanshiRouteImport } from './routes/sanshi'
import { Route as ShushuRouteImport } from './routes/shushu'
import { Route as SkyRouteImport } from './routes/sky'
import { Route as SynastryRouteImport } from './routes/synastry'
import { Route as TaixuanRouteImport } from './routes/taixuan'
import { Route as TaiyiRouteImport } from './routes/taiyi'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as TongsheRouteImport } from './routes/tongshe'
import { Route as TransitsRouteImport } from './routes/transits'
import { Route as UranianRouteImport } from './routes/uranian'
import { Route as VedicRouteImport } from './routes/vedic'
import { Route as WuzhaoRouteImport } from './routes/wuzhao'
import { Route as XiaochengRouteImport } from './routes/xiaocheng'
import { Route as XiaoliurenRouteImport } from './routes/xiaoliuren'
import { Route as XiuRouteImport } from './routes/xiu'
import { Route as ZeriRouteImport } from './routes/zeri'
import { Route as ZiweiRouteImport } from './routes/ziwei'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const AsteroidsRoute = AsteroidsRouteImport.update({
  id: '/asteroids',
  path: '/asteroids',
  getParentRoute: () => rootRouteImport,
} as any)
const BaziRoute = BaziRouteImport.update({
  id: '/bazi',
  path: '/bazi',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebsRoute = CelebsRouteImport.update({
  id: '/celebs',
  path: '/celebs',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeigongRoute = FeigongRouteImport.update({
  id: '/feigong',
  path: '/feigong',
  getParentRoute: () => rootRouteImport,
} as any)
const FengshuiRoute = FengshuiRouteImport.update({
  id: '/fengshui',
  path: '/fengshui',
  getParentRoute: () => rootRouteImport,
} as any)
const GeomancyRoute = GeomancyRouteImport.update({
  id: '/geomancy',
  path: '/geomancy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JieqiRoute = JieqiRouteImport.update({
  id: '/jieqi',
  path: '/jieqi',
  getParentRoute: () => rootRouteImport,
} as any)
const JingjueRoute = JingjueRouteImport.update({
  id: '/jingjue',
  path: '/jingjue',
  getParentRoute: () => rootRouteImport,
} as any)
const JinkouRoute = JinkouRouteImport.update({
  id: '/jinkou',
  path: '/jinkou',
  getParentRoute: () => rootRouteImport,
} as any)
const LingqiRoute = LingqiRouteImport.update({
  id: '/lingqi',
  path: '/lingqi',
  getParentRoute: () => rootRouteImport,
} as any)
const LiurenRoute = LiurenRouteImport.update({
  id: '/liuren',
  path: '/liuren',
  getParentRoute: () => rootRouteImport,
} as any)
const LiuyaoRoute = LiuyaoRouteImport.update({
  id: '/liuyao',
  path: '/liuyao',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MingotherRoute = MingotherRouteImport.update({
  id: '/mingother',
  path: '/mingother',
  getParentRoute: () => rootRouteImport,
} as any)
const NatalRoute = NatalRouteImport.update({
  id: '/natal',
  path: '/natal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const QimenRoute = QimenRouteImport.update({
  id: '/qimen',
  path: '/qimen',
  getParentRoute: () => rootRouteImport,
} as any)
const QizhengRoute = QizhengRouteImport.update({
  id: '/qizheng',
  path: '/qizheng',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SanshiRoute = SanshiRouteImport.update({
  id: '/sanshi',
  path: '/sanshi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShushuRoute = ShushuRouteImport.update({
  id: '/shushu',
  path: '/shushu',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyRoute = SkyRouteImport.update({
  id: '/sky',
  path: '/sky',
  getParentRoute: () => rootRouteImport,
} as any)
const SynastryRoute = SynastryRouteImport.update({
  id: '/synastry',
  path: '/synastry',
  getParentRoute: () => rootRouteImport,
} as any)
const TaixuanRoute = TaixuanRouteImport.update({
  id: '/taixuan',
  path: '/taixuan',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiyiRoute = TaiyiRouteImport.update({
  id: '/taiyi',
  path: '/taiyi',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const TongsheRoute = TongsheRouteImport.update({
  id: '/tongshe',
  path: '/tongshe',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsRoute = TransitsRouteImport.update({
  id: '/transits',
  path: '/transits',
  getParentRoute: () => rootRouteImport,
} as any)
const UranianRoute = UranianRouteImport.update({
  id: '/uranian',
  path: '/uranian',
  getParentRoute: () => rootRouteImport,
} as any)
const VedicRoute = VedicRouteImport.update({
  id: '/vedic',
  path: '/vedic',
  getParentRoute: () => rootRouteImport,
} as any)
const WuzhaoRoute = WuzhaoRouteImport.update({
  id: '/wuzhao',
  path: '/wuzhao',
  getParentRoute: () => rootRouteImport,
} as any)
const XiaochengRoute = XiaochengRouteImport.update({
  id: '/xiaocheng',
  path: '/xiaocheng',
  getParentRoute: () => rootRouteImport,
} as any)
const XiaoliurenRoute = XiaoliurenRouteImport.update({
  id: '/xiaoliuren',
  path: '/xiaoliuren',
  getParentRoute: () => rootRouteImport,
} as any)
const XiuRoute = XiuRouteImport.update({
  id: '/xiu',
  path: '/xiu',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeriRoute = ZeriRouteImport.update({
  id: '/zeri',
  path: '/zeri',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiweiRoute = ZiweiRouteImport.update({
  id: '/ziwei',
  path: '/ziwei',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/asteroids': typeof AsteroidsRoute
  '/bazi': typeof BaziRoute
  '/catalog': typeof CatalogRoute
  '/celebs': typeof CelebsRoute
  '/directions': typeof DirectionsRoute
  '/feigong': typeof FeigongRoute
  '/fengshui': typeof FengshuiRoute
  '/geomancy': typeof GeomancyRoute
  '/history': typeof HistoryRouteWithChildren
  '/jieqi': typeof JieqiRoute
  '/jingjue': typeof JingjueRoute
  '/jinkou': typeof JinkouRoute
  '/lingqi': typeof LingqiRoute
  '/liuren': typeof LiurenRoute
  '/liuyao': typeof LiuyaoRoute
  '/me': typeof MeRoute
  '/mingother': typeof MingotherRoute
  '/natal': typeof NatalRoute
  '/parts': typeof PartsRoute
  '/qimen': typeof QimenRoute
  '/qizheng': typeof QizhengRoute
  '/reference': typeof ReferenceRoute
  '/sanshi': typeof SanshiRoute
  '/shushu': typeof ShushuRoute
  '/sky': typeof SkyRoute
  '/synastry': typeof SynastryRoute
  '/taixuan': typeof TaixuanRoute
  '/taiyi': typeof TaiyiRoute
  '/tarot': typeof TarotRoute
  '/tongshe': typeof TongsheRoute
  '/transits': typeof TransitsRoute
  '/uranian': typeof UranianRoute
  '/vedic': typeof VedicRoute
  '/wuzhao': typeof WuzhaoRoute
  '/xiaocheng': typeof XiaochengRoute
  '/xiaoliuren': typeof XiaoliurenRoute
  '/xiu': typeof XiuRoute
  '/zeri': typeof ZeriRoute
  '/ziwei': typeof ZiweiRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/asteroids': typeof AsteroidsRoute
  '/bazi': typeof BaziRoute
  '/catalog': typeof CatalogRoute
  '/celebs': typeof CelebsRoute
  '/directions': typeof DirectionsRoute
  '/feigong': typeof FeigongRoute
  '/fengshui': typeof FengshuiRoute
  '/geomancy': typeof GeomancyRoute
  '/history': typeof HistoryRouteWithChildren
  '/jieqi': typeof JieqiRoute
  '/jingjue': typeof JingjueRoute
  '/jinkou': typeof JinkouRoute
  '/lingqi': typeof LingqiRoute
  '/liuren': typeof LiurenRoute
  '/liuyao': typeof LiuyaoRoute
  '/me': typeof MeRoute
  '/mingother': typeof MingotherRoute
  '/natal': typeof NatalRoute
  '/parts': typeof PartsRoute
  '/qimen': typeof QimenRoute
  '/qizheng': typeof QizhengRoute
  '/reference': typeof ReferenceRoute
  '/sanshi': typeof SanshiRoute
  '/shushu': typeof ShushuRoute
  '/sky': typeof SkyRoute
  '/synastry': typeof SynastryRoute
  '/taixuan': typeof TaixuanRoute
  '/taiyi': typeof TaiyiRoute
  '/tarot': typeof TarotRoute
  '/tongshe': typeof TongsheRoute
  '/transits': typeof TransitsRoute
  '/uranian': typeof UranianRoute
  '/vedic': typeof VedicRoute
  '/wuzhao': typeof WuzhaoRoute
  '/xiaocheng': typeof XiaochengRoute
  '/xiaoliuren': typeof XiaoliurenRoute
  '/xiu': typeof XiuRoute
  '/zeri': typeof ZeriRoute
  '/ziwei': typeof ZiweiRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/asteroids': typeof AsteroidsRoute
  '/bazi': typeof BaziRoute
  '/catalog': typeof CatalogRoute
  '/celebs': typeof CelebsRoute
  '/directions': typeof DirectionsRoute
  '/feigong': typeof FeigongRoute
  '/fengshui': typeof FengshuiRoute
  '/geomancy': typeof GeomancyRoute
  '/history': typeof HistoryRouteWithChildren
  '/jieqi': typeof JieqiRoute
  '/jingjue': typeof JingjueRoute
  '/jinkou': typeof JinkouRoute
  '/lingqi': typeof LingqiRoute
  '/liuren': typeof LiurenRoute
  '/liuyao': typeof LiuyaoRoute
  '/me': typeof MeRoute
  '/mingother': typeof MingotherRoute
  '/natal': typeof NatalRoute
  '/parts': typeof PartsRoute
  '/qimen': typeof QimenRoute
  '/qizheng': typeof QizhengRoute
  '/reference': typeof ReferenceRoute
  '/sanshi': typeof SanshiRoute
  '/shushu': typeof ShushuRoute
  '/sky': typeof SkyRoute
  '/synastry': typeof SynastryRoute
  '/taixuan': typeof TaixuanRoute
  '/taiyi': typeof TaiyiRoute
  '/tarot': typeof TarotRoute
  '/tongshe': typeof TongsheRoute
  '/transits': typeof TransitsRoute
  '/uranian': typeof UranianRoute
  '/vedic': typeof VedicRoute
  '/wuzhao': typeof WuzhaoRoute
  '/xiaocheng': typeof XiaochengRoute
  '/xiaoliuren': typeof XiaoliurenRoute
  '/xiu': typeof XiuRoute
  '/zeri': typeof ZeriRoute
  '/ziwei': typeof ZiweiRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/almanac'
    | '/asteroids'
    | '/bazi'
    | '/catalog'
    | '/celebs'
    | '/directions'
    | '/feigong'
    | '/fengshui'
    | '/geomancy'
    | '/history'
    | '/jieqi'
    | '/jingjue'
    | '/jinkou'
    | '/lingqi'
    | '/liuren'
    | '/liuyao'
    | '/me'
    | '/mingother'
    | '/natal'
    | '/parts'
    | '/qimen'
    | '/qizheng'
    | '/reference'
    | '/sanshi'
    | '/shushu'
    | '/sky'
    | '/synastry'
    | '/taixuan'
    | '/taiyi'
    | '/tarot'
    | '/tongshe'
    | '/transits'
    | '/uranian'
    | '/vedic'
    | '/wuzhao'
    | '/xiaocheng'
    | '/xiaoliuren'
    | '/xiu'
    | '/zeri'
    | '/ziwei'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/almanac'
    | '/asteroids'
    | '/bazi'
    | '/catalog'
    | '/celebs'
    | '/directions'
    | '/feigong'
    | '/fengshui'
    | '/geomancy'
    | '/history'
    | '/jieqi'
    | '/jingjue'
    | '/jinkou'
    | '/lingqi'
    | '/liuren'
    | '/liuyao'
    | '/me'
    | '/mingother'
    | '/natal'
    | '/parts'
    | '/qimen'
    | '/qizheng'
    | '/reference'
    | '/sanshi'
    | '/shushu'
    | '/sky'
    | '/synastry'
    | '/taixuan'
    | '/taiyi'
    | '/tarot'
    | '/tongshe'
    | '/transits'
    | '/uranian'
    | '/vedic'
    | '/wuzhao'
    | '/xiaocheng'
    | '/xiaoliuren'
    | '/xiu'
    | '/zeri'
    | '/ziwei'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/almanac'
    | '/asteroids'
    | '/bazi'
    | '/catalog'
    | '/celebs'
    | '/directions'
    | '/feigong'
    | '/fengshui'
    | '/geomancy'
    | '/history'
    | '/jieqi'
    | '/jingjue'
    | '/jinkou'
    | '/lingqi'
    | '/liuren'
    | '/liuyao'
    | '/me'
    | '/mingother'
    | '/natal'
    | '/parts'
    | '/qimen'
    | '/qizheng'
    | '/reference'
    | '/sanshi'
    | '/shushu'
    | '/sky'
    | '/synastry'
    | '/taixuan'
    | '/taiyi'
    | '/tarot'
    | '/tongshe'
    | '/transits'
    | '/uranian'
    | '/vedic'
    | '/wuzhao'
    | '/xiaocheng'
    | '/xiaoliuren'
    | '/xiu'
    | '/zeri'
    | '/ziwei'
    | '/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlmanacRoute: typeof AlmanacRoute
  AsteroidsRoute: typeof AsteroidsRoute
  BaziRoute: typeof BaziRoute
  CatalogRoute: typeof CatalogRoute
  CelebsRoute: typeof CelebsRoute
  DirectionsRoute: typeof DirectionsRoute
  FeigongRoute: typeof FeigongRoute
  FengshuiRoute: typeof FengshuiRoute
  GeomancyRoute: typeof GeomancyRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  JieqiRoute: typeof JieqiRoute
  JingjueRoute: typeof JingjueRoute
  JinkouRoute: typeof JinkouRoute
  LingqiRoute: typeof LingqiRoute
  LiurenRoute: typeof LiurenRoute
  LiuyaoRoute: typeof LiuyaoRoute
  MeRoute: typeof MeRoute
  MingotherRoute: typeof MingotherRoute
  NatalRoute: typeof NatalRoute
  PartsRoute: typeof PartsRoute
  QimenRoute: typeof QimenRoute
  QizhengRoute: typeof QizhengRoute
  ReferenceRoute: typeof ReferenceRoute
  SanshiRoute: typeof SanshiRoute
  ShushuRoute: typeof ShushuRoute
  SkyRoute: typeof SkyRoute
  SynastryRoute: typeof SynastryRoute
  TaixuanRoute: typeof TaixuanRoute
  TaiyiRoute: typeof TaiyiRoute
  TarotRoute: typeof TarotRoute
  TongsheRoute: typeof TongsheRoute
  TransitsRoute: typeof TransitsRoute
  UranianRoute: typeof UranianRoute
  VedicRoute: typeof VedicRoute
  WuzhaoRoute: typeof WuzhaoRoute
  XiaochengRoute: typeof XiaochengRoute
  XiaoliurenRoute: typeof XiaoliurenRoute
  XiuRoute: typeof XiuRoute
  ZeriRoute: typeof ZeriRoute
  ZiweiRoute: typeof ZiweiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asteroids': {
      id: '/asteroids'
      path: '/asteroids'
      fullPath: '/asteroids'
      preLoaderRoute: typeof AsteroidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazi': {
      id: '/bazi'
      path: '/bazi'
      fullPath: '/bazi'
      preLoaderRoute: typeof BaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebs': {
      id: '/celebs'
      path: '/celebs'
      fullPath: '/celebs'
      preLoaderRoute: typeof CelebsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feigong': {
      id: '/feigong'
      path: '/feigong'
      fullPath: '/feigong'
      preLoaderRoute: typeof FeigongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fengshui': {
      id: '/fengshui'
      path: '/fengshui'
      fullPath: '/fengshui'
      preLoaderRoute: typeof FengshuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geomancy': {
      id: '/geomancy'
      path: '/geomancy'
      fullPath: '/geomancy'
      preLoaderRoute: typeof GeomancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jieqi': {
      id: '/jieqi'
      path: '/jieqi'
      fullPath: '/jieqi'
      preLoaderRoute: typeof JieqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jingjue': {
      id: '/jingjue'
      path: '/jingjue'
      fullPath: '/jingjue'
      preLoaderRoute: typeof JingjueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinkou': {
      id: '/jinkou'
      path: '/jinkou'
      fullPath: '/jinkou'
      preLoaderRoute: typeof JinkouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lingqi': {
      id: '/lingqi'
      path: '/lingqi'
      fullPath: '/lingqi'
      preLoaderRoute: typeof LingqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liuren': {
      id: '/liuren'
      path: '/liuren'
      fullPath: '/liuren'
      preLoaderRoute: typeof LiurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liuyao': {
      id: '/liuyao'
      path: '/liuyao'
      fullPath: '/liuyao'
      preLoaderRoute: typeof LiuyaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mingother': {
      id: '/mingother'
      path: '/mingother'
      fullPath: '/mingother'
      preLoaderRoute: typeof MingotherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natal': {
      id: '/natal'
      path: '/natal'
      fullPath: '/natal'
      preLoaderRoute: typeof NatalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qimen': {
      id: '/qimen'
      path: '/qimen'
      fullPath: '/qimen'
      preLoaderRoute: typeof QimenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qizheng': {
      id: '/qizheng'
      path: '/qizheng'
      fullPath: '/qizheng'
      preLoaderRoute: typeof QizhengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanshi': {
      id: '/sanshi'
      path: '/sanshi'
      fullPath: '/sanshi'
      preLoaderRoute: typeof SanshiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shushu': {
      id: '/shushu'
      path: '/shushu'
      fullPath: '/shushu'
      preLoaderRoute: typeof ShushuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sky': {
      id: '/sky'
      path: '/sky'
      fullPath: '/sky'
      preLoaderRoute: typeof SkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synastry': {
      id: '/synastry'
      path: '/synastry'
      fullPath: '/synastry'
      preLoaderRoute: typeof SynastryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taixuan': {
      id: '/taixuan'
      path: '/taixuan'
      fullPath: '/taixuan'
      preLoaderRoute: typeof TaixuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taiyi': {
      id: '/taiyi'
      path: '/taiyi'
      fullPath: '/taiyi'
      preLoaderRoute: typeof TaiyiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tongshe': {
      id: '/tongshe'
      path: '/tongshe'
      fullPath: '/tongshe'
      preLoaderRoute: typeof TongsheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits': {
      id: '/transits'
      path: '/transits'
      fullPath: '/transits'
      preLoaderRoute: typeof TransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uranian': {
      id: '/uranian'
      path: '/uranian'
      fullPath: '/uranian'
      preLoaderRoute: typeof UranianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vedic': {
      id: '/vedic'
      path: '/vedic'
      fullPath: '/vedic'
      preLoaderRoute: typeof VedicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wuzhao': {
      id: '/wuzhao'
      path: '/wuzhao'
      fullPath: '/wuzhao'
      preLoaderRoute: typeof WuzhaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xiaocheng': {
      id: '/xiaocheng'
      path: '/xiaocheng'
      fullPath: '/xiaocheng'
      preLoaderRoute: typeof XiaochengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xiaoliuren': {
      id: '/xiaoliuren'
      path: '/xiaoliuren'
      fullPath: '/xiaoliuren'
      preLoaderRoute: typeof XiaoliurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xiu': {
      id: '/xiu'
      path: '/xiu'
      fullPath: '/xiu'
      preLoaderRoute: typeof XiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zeri': {
      id: '/zeri'
      path: '/zeri'
      fullPath: '/zeri'
      preLoaderRoute: typeof ZeriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziwei': {
      id: '/ziwei'
      path: '/ziwei'
      fullPath: '/ziwei'
      preLoaderRoute: typeof ZiweiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlmanacRoute: AlmanacRoute,
  AsteroidsRoute: AsteroidsRoute,
  BaziRoute: BaziRoute,
  CatalogRoute: CatalogRoute,
  CelebsRoute: CelebsRoute,
  DirectionsRoute: DirectionsRoute,
  FeigongRoute: FeigongRoute,
  FengshuiRoute: FengshuiRoute,
  GeomancyRoute: GeomancyRoute,
  HistoryRoute: HistoryRouteWithChildren,
  JieqiRoute: JieqiRoute,
  JingjueRoute: JingjueRoute,
  JinkouRoute: JinkouRoute,
  LingqiRoute: LingqiRoute,
  LiurenRoute: LiurenRoute,
  LiuyaoRoute: LiuyaoRoute,
  MeRoute: MeRoute,
  MingotherRoute: MingotherRoute,
  NatalRoute: NatalRoute,
  PartsRoute: PartsRoute,
  QimenRoute: QimenRoute,
  QizhengRoute: QizhengRoute,
  ReferenceRoute: ReferenceRoute,
  SanshiRoute: SanshiRoute,
  ShushuRoute: ShushuRoute,
  SkyRoute: SkyRoute,
  SynastryRoute: SynastryRoute,
  TaixuanRoute: TaixuanRoute,
  TaiyiRoute: TaiyiRoute,
  TarotRoute: TarotRoute,
  TongsheRoute: TongsheRoute,
  TransitsRoute: TransitsRoute,
  UranianRoute: UranianRoute,
  VedicRoute: VedicRoute,
  WuzhaoRoute: WuzhaoRoute,
  XiaochengRoute: XiaochengRoute,
  XiaoliurenRoute: XiaoliurenRoute,
  XiuRoute: XiuRoute,
  ZeriRoute: ZeriRoute,
  ZiweiRoute: ZiweiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
