/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as BaziRouteImport } from './routes/bazi'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CelebsRouteImport } from './routes/celebs'
import { Route as FengshuiRouteImport } from './routes/fengshui'
import { Route as GeomancyRouteImport } from './routes/geomancy'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JinkouRouteImport } from './routes/jinkou'
import { Route as LiurenRouteImport } from './routes/liuren'
import { Route as LiuyaoRouteImport } from './routes/liuyao'
import { Route as MeRouteImport } from './routes/me'
import { Route as NatalRouteImport } from './routes/natal'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as QimenRouteImport } from './routes/qimen'
import { Route as QizhengRouteImport } from './routes/qizheng'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as SanshiRouteImport } from './routes/sanshi'
import { Route as ShushuRouteImport } from './routes/shushu'
import { Route as SkyRouteImport } from './routes/sky'
import { Route as SynastryRouteImport } from './routes/synastry'
import { Route as TaixuanRouteImport } from './routes/taixuan'
import { Route as TaiyiRouteImport } from './routes/taiyi'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as TransitsRouteImport } from './routes/transits'
import { Route as VedicRouteImport } from './routes/vedic'
import { Route as ZiweiRouteImport } from './routes/ziwei'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const BaziRoute = BaziRouteImport.update({
  id: '/bazi',
  path: '/bazi',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebsRoute = CelebsRouteImport.update({
  id: '/celebs',
  path: '/celebs',
  getParentRoute: () => rootRouteImport,
} as any)
const FengshuiRoute = FengshuiRouteImport.update({
  id: '/fengshui',
  path: '/fengshui',
  getParentRoute: () => rootRouteImport,
} as any)
const GeomancyRoute = GeomancyRouteImport.update({
  id: '/geomancy',
  path: '/geomancy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JinkouRoute = JinkouRouteImport.update({
  id: '/jinkou',
  path: '/jinkou',
  getParentRoute: () => rootRouteImport,
} as any)
const LiurenRoute = LiurenRouteImport.update({
  id: '/liuren',
  path: '/liuren',
  getParentRoute: () => rootRouteImport,
} as any)
const LiuyaoRoute = LiuyaoRouteImport.update({
  id: '/liuyao',
  path: '/liuyao',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NatalRoute = NatalRouteImport.update({
  id: '/natal',
  path: '/natal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const QimenRoute = QimenRouteImport.update({
  id: '/qimen',
  path: '/qimen',
  getParentRoute: () => rootRouteImport,
} as any)
const QizhengRoute = QizhengRouteImport.update({
  id: '/qizheng',
  path: '/qizheng',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SanshiRoute = SanshiRouteImport.update({
  id: '/sanshi',
  path: '/sanshi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShushuRoute = ShushuRouteImport.update({
  id: '/shushu',
  path: '/shushu',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyRoute = SkyRouteImport.update({
  id: '/sky',
  path: '/sky',
  getParentRoute: () => rootRouteImport,
} as any)
const SynastryRoute = SynastryRouteImport.update({
  id: '/synastry',
  path: '/synastry',
  getParentRoute: () => rootRouteImport,
} as any)
const TaixuanRoute = TaixuanRouteImport.update({
  id: '/taixuan',
  path: '/taixuan',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiyiRoute = TaiyiRouteImport.update({
  id: '/taiyi',
  path: '/taiyi',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsRoute = TransitsRouteImport.update({
  id: '/transits',
  path: '/transits',
  getParentRoute: () => rootRouteImport,
} as any)
const VedicRoute = VedicRouteImport.update({
  id: '/vedic',
  path: '/vedic',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiweiRoute = ZiweiRouteImport.update({
  id: '/ziwei',
  path: '/ziwei',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/bazi': typeof BaziRoute
  '/catalog': typeof CatalogRoute
  '/celebs': typeof CelebsRoute
  '/fengshui': typeof FengshuiRoute
  '/geomancy': typeof GeomancyRoute
  '/history': typeof HistoryRouteWithChildren
  '/jinkou': typeof JinkouRoute
  '/liuren': typeof LiurenRoute
  '/liuyao': typeof LiuyaoRoute
  '/me': typeof MeRoute
  '/natal': typeof NatalRoute
  '/parts': typeof PartsRoute
  '/qimen': typeof QimenRoute
  '/qizheng': typeof QizhengRoute
  '/reference': typeof ReferenceRoute
  '/sanshi': typeof SanshiRoute
  '/shushu': typeof ShushuRoute
  '/sky': typeof SkyRoute
  '/synastry': typeof SynastryRoute
  '/taixuan': typeof TaixuanRoute
  '/taiyi': typeof TaiyiRoute
  '/tarot': typeof TarotRoute
  '/transits': typeof TransitsRoute
  '/vedic': typeof VedicRoute
  '/ziwei': typeof ZiweiRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/bazi': typeof BaziRoute
  '/catalog': typeof CatalogRoute
  '/celebs': typeof CelebsRoute
  '/fengshui': typeof FengshuiRoute
  '/geomancy': typeof GeomancyRoute
  '/history': typeof HistoryRouteWithChildren
  '/jinkou': typeof JinkouRoute
  '/liuren': typeof LiurenRoute
  '/liuyao': typeof LiuyaoRoute
  '/me': typeof MeRoute
  '/natal': typeof NatalRoute
  '/parts': typeof PartsRoute
  '/qimen': typeof QimenRoute
  '/qizheng': typeof QizhengRoute
  '/reference': typeof ReferenceRoute
  '/sanshi': typeof SanshiRoute
  '/shushu': typeof ShushuRoute
  '/sky': typeof SkyRoute
  '/synastry': typeof SynastryRoute
  '/taixuan': typeof TaixuanRoute
  '/taiyi': typeof TaiyiRoute
  '/tarot': typeof TarotRoute
  '/transits': typeof TransitsRoute
  '/vedic': typeof VedicRoute
  '/ziwei': typeof ZiweiRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/almanac': typeof AlmanacRoute
  '/bazi': typeof BaziRoute
  '/catalog': typeof CatalogRoute
  '/celebs': typeof CelebsRoute
  '/fengshui': typeof FengshuiRoute
  '/geomancy': typeof GeomancyRoute
  '/history': typeof HistoryRouteWithChildren
  '/jinkou': typeof JinkouRoute
  '/liuren': typeof LiurenRoute
  '/liuyao': typeof LiuyaoRoute
  '/me': typeof MeRoute
  '/natal': typeof NatalRoute
  '/parts': typeof PartsRoute
  '/qimen': typeof QimenRoute
  '/qizheng': typeof QizhengRoute
  '/reference': typeof ReferenceRoute
  '/sanshi': typeof SanshiRoute
  '/shushu': typeof ShushuRoute
  '/sky': typeof SkyRoute
  '/synastry': typeof SynastryRoute
  '/taixuan': typeof TaixuanRoute
  '/taiyi': typeof TaiyiRoute
  '/tarot': typeof TarotRoute
  '/transits': typeof TransitsRoute
  '/vedic': typeof VedicRoute
  '/ziwei': typeof ZiweiRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/almanac'
    | '/bazi'
    | '/catalog'
    | '/celebs'
    | '/fengshui'
    | '/geomancy'
    | '/history'
    | '/jinkou'
    | '/liuren'
    | '/liuyao'
    | '/me'
    | '/natal'
    | '/parts'
    | '/qimen'
    | '/qizheng'
    | '/reference'
    | '/sanshi'
    | '/shushu'
    | '/sky'
    | '/synastry'
    | '/taixuan'
    | '/taiyi'
    | '/tarot'
    | '/transits'
    | '/vedic'
    | '/ziwei'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/almanac'
    | '/bazi'
    | '/catalog'
    | '/celebs'
    | '/fengshui'
    | '/geomancy'
    | '/history'
    | '/jinkou'
    | '/liuren'
    | '/liuyao'
    | '/me'
    | '/natal'
    | '/parts'
    | '/qimen'
    | '/qizheng'
    | '/reference'
    | '/sanshi'
    | '/shushu'
    | '/sky'
    | '/synastry'
    | '/taixuan'
    | '/taiyi'
    | '/tarot'
    | '/transits'
    | '/vedic'
    | '/ziwei'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/almanac'
    | '/bazi'
    | '/catalog'
    | '/celebs'
    | '/fengshui'
    | '/geomancy'
    | '/history'
    | '/jinkou'
    | '/liuren'
    | '/liuyao'
    | '/me'
    | '/natal'
    | '/parts'
    | '/qimen'
    | '/qizheng'
    | '/reference'
    | '/sanshi'
    | '/shushu'
    | '/sky'
    | '/synastry'
    | '/taixuan'
    | '/taiyi'
    | '/tarot'
    | '/transits'
    | '/vedic'
    | '/ziwei'
    | '/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlmanacRoute: typeof AlmanacRoute
  BaziRoute: typeof BaziRoute
  CatalogRoute: typeof CatalogRoute
  CelebsRoute: typeof CelebsRoute
  FengshuiRoute: typeof FengshuiRoute
  GeomancyRoute: typeof GeomancyRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  JinkouRoute: typeof JinkouRoute
  LiurenRoute: typeof LiurenRoute
  LiuyaoRoute: typeof LiuyaoRoute
  MeRoute: typeof MeRoute
  NatalRoute: typeof NatalRoute
  PartsRoute: typeof PartsRoute
  QimenRoute: typeof QimenRoute
  QizhengRoute: typeof QizhengRoute
  ReferenceRoute: typeof ReferenceRoute
  SanshiRoute: typeof SanshiRoute
  ShushuRoute: typeof ShushuRoute
  SkyRoute: typeof SkyRoute
  SynastryRoute: typeof SynastryRoute
  TaixuanRoute: typeof TaixuanRoute
  TaiyiRoute: typeof TaiyiRoute
  TarotRoute: typeof TarotRoute
  TransitsRoute: typeof TransitsRoute
  VedicRoute: typeof VedicRoute
  ZiweiRoute: typeof ZiweiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazi': {
      id: '/bazi'
      path: '/bazi'
      fullPath: '/bazi'
      preLoaderRoute: typeof BaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebs': {
      id: '/celebs'
      path: '/celebs'
      fullPath: '/celebs'
      preLoaderRoute: typeof CelebsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fengshui': {
      id: '/fengshui'
      path: '/fengshui'
      fullPath: '/fengshui'
      preLoaderRoute: typeof FengshuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geomancy': {
      id: '/geomancy'
      path: '/geomancy'
      fullPath: '/geomancy'
      preLoaderRoute: typeof GeomancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinkou': {
      id: '/jinkou'
      path: '/jinkou'
      fullPath: '/jinkou'
      preLoaderRoute: typeof JinkouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liuren': {
      id: '/liuren'
      path: '/liuren'
      fullPath: '/liuren'
      preLoaderRoute: typeof LiurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liuyao': {
      id: '/liuyao'
      path: '/liuyao'
      fullPath: '/liuyao'
      preLoaderRoute: typeof LiuyaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natal': {
      id: '/natal'
      path: '/natal'
      fullPath: '/natal'
      preLoaderRoute: typeof NatalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qimen': {
      id: '/qimen'
      path: '/qimen'
      fullPath: '/qimen'
      preLoaderRoute: typeof QimenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qizheng': {
      id: '/qizheng'
      path: '/qizheng'
      fullPath: '/qizheng'
      preLoaderRoute: typeof QizhengRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanshi': {
      id: '/sanshi'
      path: '/sanshi'
      fullPath: '/sanshi'
      preLoaderRoute: typeof SanshiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shushu': {
      id: '/shushu'
      path: '/shushu'
      fullPath: '/shushu'
      preLoaderRoute: typeof ShushuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sky': {
      id: '/sky'
      path: '/sky'
      fullPath: '/sky'
      preLoaderRoute: typeof SkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synastry': {
      id: '/synastry'
      path: '/synastry'
      fullPath: '/synastry'
      preLoaderRoute: typeof SynastryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taixuan': {
      id: '/taixuan'
      path: '/taixuan'
      fullPath: '/taixuan'
      preLoaderRoute: typeof TaixuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taiyi': {
      id: '/taiyi'
      path: '/taiyi'
      fullPath: '/taiyi'
      preLoaderRoute: typeof TaiyiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits': {
      id: '/transits'
      path: '/transits'
      fullPath: '/transits'
      preLoaderRoute: typeof TransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vedic': {
      id: '/vedic'
      path: '/vedic'
      fullPath: '/vedic'
      preLoaderRoute: typeof VedicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziwei': {
      id: '/ziwei'
      path: '/ziwei'
      fullPath: '/ziwei'
      preLoaderRoute: typeof ZiweiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlmanacRoute: AlmanacRoute,
  BaziRoute: BaziRoute,
  CatalogRoute: CatalogRoute,
  CelebsRoute: CelebsRoute,
  FengshuiRoute: FengshuiRoute,
  GeomancyRoute: GeomancyRoute,
  HistoryRoute: HistoryRouteWithChildren,
  JinkouRoute: JinkouRoute,
  LiurenRoute: LiurenRoute,
  LiuyaoRoute: LiuyaoRoute,
  MeRoute: MeRoute,
  NatalRoute: NatalRoute,
  PartsRoute: PartsRoute,
  QimenRoute: QimenRoute,
  QizhengRoute: QizhengRoute,
  ReferenceRoute: ReferenceRoute,
  SanshiRoute: SanshiRoute,
  ShushuRoute: ShushuRoute,
  SkyRoute: SkyRoute,
  SynastryRoute: SynastryRoute,
  TaixuanRoute: TaixuanRoute,
  TaiyiRoute: TaiyiRoute,
  TarotRoute: TarotRoute,
  TransitsRoute: TransitsRoute,
  VedicRoute: VedicRoute,
  ZiweiRoute: ZiweiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
